export const modules = [
  "Architecture et Calcul Parallèle",
  "Administration et Gestion des grilles de calcul",
  "Administration réseaux",
  "Algebre",
  "Algebre 3",
  "Algo 1",
  "Algo 3",
  "Algo & structures de données ou Electromagnétisme",
  "Algorithmique Avancée et Complexité",
  "Analyse discriminante et segmentation",
  "Analyse",
  "Analyse 3",
  "Analyse numerique",
  "Anglais",
  "Archi 1",
  "Archi 2",
  "Architecture des Bases de données",
  "Architecture et Administration de SGBD",
  "Architecture et Administration de bases de Données",
  "Architecture et administration des réseaux",
  "Architectures Avancées",
  "Architectures des réseaux informatiques",
  "Arithmétique modulaire",
  "Aspects juridiques dans la sécurité informatique",
  "Assurance Qualité des Logiciels",
  "Audit de sécurité",
  "Bases de Données Avancées et Big Data",
  "Bioinfo et Génomique",
  "Biomathématique",
  "Biostatistique",
  "Biométrie et Sécurisation de Données",
  "Bases de Données 2",
  "Bases de données Avancées",
  "Bureautique et Web",
  "Calcul Embarqué",
  "Calcul parallèle et grilles de calcul",
  "Communication Multimédia",
  "Compilation",
  "Compilation : génération du code et optimisation",
  "Concepts Avancés du Génie Logiciel",
  "Construction de systèmes Parallèles",
  "Construction d’applications réparties",
  "Décision dans l’incertain",
  "Data Mining",
  "Electronique analogique",
  "Electronique numérique",
  "Entreprenariat",
  "Fouille de Données2",
  "Gestion de projet",
  "Gestion de Projet de Développement de Logiciels",
  "Graphes et Big Data",
  "Génie Logiciel 2",
  "Génie Logiciel et POO",
  "Imagerie Médicale et Parallélisme",
  "Introduction aux systèmes d’exploitation 1",
  "Introduction à la sécurité informatique",
  "Logique",
  "Méthodes Conceptuelles d’Analyse",
  "Modélisation des systèmes communicants",
  "Modélisation et Evaluation des performances des systèmes",
  "Modélisation et Simulation",
  "Méthodes d’optimisation",
  "Méthodes pratiques et outils de détection d’intrusions",
  "Méthodologie et Processus de Développement de Logiciels",
  "Optimisation discrète",
  "Optimisation linéaire",
  "Option",
  "POO",
  "Physique",
  "Proba",
  "Proba 2",
  "Programmation Multi-Cœurs",
  "Programmation Web",
  "Programmation Web Avancée",
  "Programmation avancée",
  "Programmation et sûreté des systèmes répartis",
  "Programmation par contraintes",
  "Programmation réseau",
  "Recherche d’information",
  "Représentation de connaissances et raisonnement",
  "Représentation de connaissances et raisonnement 2",
  "Reseaux",
  "Réseaux Mobiles",
  "Réseaux et Protocoles",
  "Réseaux et communication sans fil",
  "Réseaux sans fil",
  "Résolution de problèmes",
  "Systèmes Embarqués",
  "SFSD",
  "SI",
  "SI 2",
  "Solveurs pour l’optimisation",
  "Système et Programmation de Scripts",
  "Stratégie de sécurité pour l’aide à la décision",
  "Strm 1",
  "Synthèses d’images",
  "Syst. de communication analogiques et numériques",
  "Système d’exploitation 2",
  "Systèmes Décisionnels et Entrepôts",
  "Systèmes d'exploitation des ordinateurs multiprocesseurs",
  "Systèmes de Télécom. et interopérabilité des réseaux",
  "Systèmes d’Information Coopératifs",
  "Système d’exploitation",
  "Systèmes d’exploitation Mobiles",
  "Systèmes d’exploitation distribués",
  "Systèmes embarqués et applications en environnement mobile",
  "Sécurité applicative",
  "Sécurité et contrôle du trafic réseau",
  "Sécurité système avancée",
  "Technologies Business Intelligence",
  "TCE",
  "Technologies de l’IA appliquées aux données",
  "Techniques de modélisation en traitement du signal",
  "Techniques de modélisation et de traitement en mécanique des fluides",
  "Théorie de l’info. caractérisation de la transmission",
  "Théorie de l’ordonnancement",
  "Théorie des graphes",
  "Théorie des jeux",
  "Traitement automatique du langage naturel",
  "Traitement et analyse d’images",
  "Transmissions réseaux et codage d’information",
  "Téléphonie, Téléphonie mobile et IP",
  "Utilisation et administration des systèmes d’exploitation",
  "Visualisation de Données et réalité Augmentée",
  "Veille Technologie",
  "Veille technologique et Bases de données avancées",
  "Vision artificielle",
  "Visualisation de données",
];
