export const roomData = [
  {
    nom: "101",
    type: "TD",
    capacite: 34,
    disponibilite: ["mardi", "lundi", "samedi", "mercredi", "jeudi"],
  },
  {
    nom: "102",
    type: "TD",
    capacite: 31,
    disponibilite: ["jeudi", "samedi", "lundi", "dimanche", "mardi"],
  },
  {
    nom: "103",
    type: "TD",
    capacite: 30,
    disponibilite: ["dimanche", "samedi", "lundi", "mercredi", "mardi"],
  },
  {
    nom: "104",
    type: "TD",
    capacite: 29,
    disponibilite: ["samedi", "mercredi", "lundi"],
  },
  {
    nom: "105",
    type: "TD",
    capacite: 31,
    disponibilite: ["samedi", "mardi", "dimanche", "jeudi"],
  },
  {
    nom: "106",
    type: "TD",
    capacite: 28,
    disponibilite: ["jeudi", "dimanche", "mercredi", "mardi"],
  },
  {
    nom: "107",
    type: "TD",
    capacite: 29,
    disponibilite: ["lundi", "mercredi", "mardi"],
  },
  {
    nom: "108",
    type: "TD",
    capacite: 35,
    disponibilite: ["samedi", "jeudi", "mercredi", "lundi"],
  },
  {
    nom: "109",
    type: "TD",
    capacite: 29,
    disponibilite: ["mercredi", "jeudi", "dimanche", "samedi", "mardi"],
  },
  {
    nom: "110",
    type: "TD",
    capacite: 30,
    disponibilite: ["mardi", "samedi", "jeudi", "dimanche", "mercredi"],
  },
  {
    nom: "111",
    type: "TD",
    capacite: 32,
    disponibilite: ["mercredi", "lundi", "dimanche", "jeudi"],
  },
  {
    nom: "112",
    type: "TD",
    capacite: 30,
    disponibilite: ["mercredi", "mardi", "jeudi", "dimanche", "lundi"],
  },
  {
    nom: "113",
    type: "TD",
    capacite: 25,
    disponibilite: ["mardi", "samedi", "jeudi", "dimanche", "mercredi"],
  },
  {
    nom: "114",
    type: "TD",
    capacite: 34,
    disponibilite: ["jeudi", "mardi", "mercredi"],
  },
  {
    nom: "115",
    type: "TD",
    capacite: 35,
    disponibilite: ["mardi", "lundi", "samedi", "mercredi", "dimanche"],
  },
  {
    nom: "116",
    type: "TD",
    capacite: 31,
    disponibilite: ["samedi", "mercredi", "dimanche", "lundi"],
  },
  {
    nom: "117",
    type: "TD",
    capacite: 30,
    disponibilite: ["mercredi", "samedi", "jeudi", "mardi"],
  },
  {
    nom: "118",
    type: "TD",
    capacite: 27,
    disponibilite: ["samedi", "dimanche", "mercredi"],
  },
  {
    nom: "119",
    type: "TD",
    capacite: 30,
    disponibilite: ["mercredi", "mardi", "samedi"],
  },
  {
    nom: "120",
    type: "TD",
    capacite: 33,
    disponibilite: ["samedi", "jeudi", "lundi", "mercredi"],
  },
  {
    nom: "121",
    type: "TD",
    capacite: 30,
    disponibilite: ["mercredi", "mardi", "jeudi", "lundi"],
  },
  {
    nom: "122",
    type: "TD",
    capacite: 34,
    disponibilite: ["lundi", "jeudi", "dimanche"],
  },
  {
    nom: "123",
    type: "TD",
    capacite: 26,
    disponibilite: ["mercredi", "mardi", "samedi", "lundi"],
  },
  {
    nom: "124",
    type: "TD",
    capacite: 25,
    disponibilite: ["dimanche", "mercredi", "lundi", "mardi", "samedi"],
  },
  {
    nom: "125",
    type: "TD",
    capacite: 35,
    disponibilite: ["dimanche", "mardi", "mercredi"],
  },
  {
    nom: "126",
    type: "TD",
    capacite: 34,
    disponibilite: ["jeudi", "dimanche", "mercredi"],
  },
  {
    nom: "127",
    type: "TD",
    capacite: 34,
    disponibilite: ["lundi", "mercredi", "samedi", "jeudi"],
  },
  {
    nom: "128",
    type: "TD",
    capacite: 30,
    disponibilite: ["lundi", "dimanche", "mardi", "jeudi"],
  },
  {
    nom: "129",
    type: "TD",
    capacite: 34,
    disponibilite: ["samedi", "mardi", "dimanche", "lundi", "mercredi"],
  },
  {
    nom: "130",
    type: "TD",
    capacite: 27,
    disponibilite: ["samedi", "jeudi", "mercredi", "mardi"],
  },
  {
    nom: "131",
    type: "TD",
    capacite: 25,
    disponibilite: ["lundi", "samedi", "mercredi", "mardi", "jeudi"],
  },
  {
    nom: "132",
    type: "TD",
    capacite: 33,
    disponibilite: ["dimanche", "mardi", "jeudi", "samedi", "lundi"],
  },
  {
    nom: "133",
    type: "TD",
    capacite: 29,
    disponibilite: ["jeudi", "dimanche", "mardi", "lundi", "mercredi"],
  },
  {
    nom: "134",
    type: "TD",
    capacite: 25,
    disponibilite: ["mardi", "mercredi", "dimanche"],
  },
  {
    nom: "135",
    type: "TD",
    capacite: 27,
    disponibilite: ["mardi", "samedi", "jeudi", "mercredi"],
  },
  {
    nom: "136",
    type: "TD",
    capacite: 31,
    disponibilite: ["dimanche", "jeudi", "mercredi", "samedi", "lundi"],
  },
  {
    nom: "137",
    type: "TD",
    capacite: 26,
    disponibilite: ["jeudi", "mercredi", "mardi", "samedi"],
  },
  {
    nom: "138",
    type: "TD",
    capacite: 35,
    disponibilite: ["jeudi", "dimanche", "lundi", "mardi"],
  },
  {
    nom: "139",
    type: "TD",
    capacite: 27,
    disponibilite: ["jeudi", "mardi", "dimanche"],
  },
  {
    nom: "140",
    type: "TD",
    capacite: 32,
    disponibilite: ["dimanche", "samedi", "mardi", "mercredi", "lundi"],
  },
  {
    nom: "141",
    type: "TD",
    capacite: 25,
    disponibilite: ["lundi", "mardi", "mercredi"],
  },
  {
    nom: "142",
    type: "TD",
    capacite: 27,
    disponibilite: ["dimanche", "mercredi", "mardi", "lundi"],
  },
  {
    nom: "143",
    type: "TD",
    capacite: 33,
    disponibilite: ["jeudi", "mardi", "mercredi", "dimanche"],
  },
  {
    nom: "144",
    type: "TD",
    capacite: 25,
    disponibilite: ["jeudi", "lundi", "mercredi", "mardi", "samedi"],
  },
  {
    nom: "145",
    type: "TD",
    capacite: 28,
    disponibilite: ["mercredi", "mardi", "jeudi", "lundi"],
  },
  {
    nom: "146",
    type: "TD",
    capacite: 30,
    disponibilite: ["mardi", "mercredi", "lundi", "dimanche", "jeudi"],
  },
  {
    nom: "147",
    type: "TD",
    capacite: 31,
    disponibilite: ["jeudi", "dimanche", "mercredi"],
  },
  {
    nom: "148",
    type: "TD",
    capacite: 27,
    disponibilite: ["jeudi", "mardi", "dimanche", "samedi", "mercredi"],
  },
  {
    nom: "149",
    type: "TD",
    capacite: 33,
    disponibilite: ["lundi", "jeudi", "dimanche"],
  },
  {
    nom: "150",
    type: "TD",
    capacite: 28,
    disponibilite: ["jeudi", "samedi", "mercredi"],
  },
  {
    nom: "151",
    type: "TD",
    capacite: 33,
    disponibilite: ["mercredi", "lundi", "mardi", "samedi"],
  },
  {
    nom: "152",
    type: "TD",
    capacite: 25,
    disponibilite: ["mercredi", "lundi", "dimanche", "jeudi"],
  },
  {
    nom: "153",
    type: "TD",
    capacite: 31,
    disponibilite: ["lundi", "mardi", "jeudi", "mercredi", "dimanche"],
  },
  {
    nom: "154",
    type: "TD",
    capacite: 31,
    disponibilite: ["samedi", "jeudi", "mardi"],
  },
  {
    nom: "155",
    type: "TD",
    capacite: 33,
    disponibilite: ["dimanche", "mardi", "lundi"],
  },
  {
    nom: "156",
    type: "TD",
    capacite: 34,
    disponibilite: ["jeudi", "lundi", "mardi", "samedi", "mercredi"],
  },
  {
    nom: "157",
    type: "TD",
    capacite: 25,
    disponibilite: ["jeudi", "mardi", "dimanche"],
  },
  {
    nom: "158",
    type: "TD",
    capacite: 29,
    disponibilite: ["dimanche", "samedi", "lundi", "jeudi", "mercredi"],
  },
  {
    nom: "159",
    type: "TD",
    capacite: 33,
    disponibilite: ["mercredi", "dimanche", "lundi"],
  },
  {
    nom: "160",
    type: "TD",
    capacite: 27,
    disponibilite: ["dimanche", "lundi", "mardi"],
  },
  {
    nom: "161",
    type: "TD",
    capacite: 34,
    disponibilite: ["mercredi", "dimanche", "samedi"],
  },
  {
    nom: "162",
    type: "TD",
    capacite: 25,
    disponibilite: ["lundi", "mardi", "dimanche", "samedi"],
  },
  {
    nom: "163",
    type: "TD",
    capacite: 29,
    disponibilite: ["lundi", "jeudi", "samedi", "dimanche"],
  },
  {
    nom: "164",
    type: "TD",
    capacite: 34,
    disponibilite: ["jeudi", "mercredi", "dimanche"],
  },
  {
    nom: "165",
    type: "TD",
    capacite: 30,
    disponibilite: ["mercredi", "mardi", "samedi", "jeudi", "dimanche"],
  },
  {
    nom: "166",
    type: "TD",
    capacite: 27,
    disponibilite: ["mercredi", "jeudi", "mardi", "samedi"],
  },
  {
    nom: "167",
    type: "TD",
    capacite: 26,
    disponibilite: ["mardi", "lundi", "mercredi", "dimanche"],
  },
  {
    nom: "168",
    type: "TD",
    capacite: 32,
    disponibilite: ["lundi", "mardi", "mercredi", "samedi"],
  },
  {
    nom: "169",
    type: "TD",
    capacite: 31,
    disponibilite: ["mardi", "lundi", "samedi"],
  },
  {
    nom: "170",
    type: "TD",
    capacite: 30,
    disponibilite: ["lundi", "mercredi", "dimanche", "mardi", "samedi"],
  },
  {
    nom: "171",
    type: "TD",
    capacite: 33,
    disponibilite: ["mardi", "jeudi", "lundi", "dimanche", "mercredi"],
  },
  {
    nom: "172",
    type: "TD",
    capacite: 34,
    disponibilite: ["mercredi", "jeudi", "lundi"],
  },
  {
    nom: "173",
    type: "TD",
    capacite: 27,
    disponibilite: ["samedi", "mardi", "mercredi"],
  },
  {
    nom: "174",
    type: "TD",
    capacite: 32,
    disponibilite: ["dimanche", "mardi", "samedi", "lundi", "jeudi"],
  },
  {
    nom: "175",
    type: "TD",
    capacite: 27,
    disponibilite: ["jeudi", "samedi", "mardi", "dimanche"],
  },
  {
    nom: "176",
    type: "TD",
    capacite: 28,
    disponibilite: ["lundi", "mardi", "samedi", "dimanche"],
  },
  {
    nom: "177",
    type: "TD",
    capacite: 34,
    disponibilite: ["jeudi", "dimanche", "mardi", "lundi"],
  },
  {
    nom: "178",
    type: "TD",
    capacite: 28,
    disponibilite: ["lundi", "dimanche", "mercredi"],
  },
  {
    nom: "179",
    type: "TD",
    capacite: 33,
    disponibilite: ["dimanche", "mercredi", "samedi", "lundi", "jeudi"],
  },
  {
    nom: "180",
    type: "TD",
    capacite: 32,
    disponibilite: ["mardi", "dimanche", "mercredi"],
  },
  {
    nom: "181",
    type: "TD",
    capacite: 30,
    disponibilite: ["samedi", "mercredi", "dimanche", "lundi"],
  },
  {
    nom: "182",
    type: "TD",
    capacite: 29,
    disponibilite: ["mercredi", "lundi", "jeudi"],
  },
  {
    nom: "183",
    type: "TD",
    capacite: 34,
    disponibilite: ["jeudi", "mercredi", "samedi"],
  },
  {
    nom: "184",
    type: "TD",
    capacite: 34,
    disponibilite: ["mercredi", "mardi", "jeudi", "lundi"],
  },
  {
    nom: "185",
    type: "TD",
    capacite: 33,
    disponibilite: ["samedi", "mercredi", "mardi", "dimanche"],
  },
  {
    nom: "186",
    type: "TD",
    capacite: 33,
    disponibilite: ["mardi", "samedi", "lundi", "mercredi", "dimanche"],
  },
  {
    nom: "187",
    type: "TD",
    capacite: 25,
    disponibilite: ["samedi", "mercredi", "jeudi", "mardi"],
  },
  {
    nom: "188",
    type: "TD",
    capacite: 28,
    disponibilite: ["dimanche", "lundi", "samedi"],
  },
  {
    nom: "189",
    type: "TD",
    capacite: 31,
    disponibilite: ["lundi", "samedi", "dimanche"],
  },
  {
    nom: "190",
    type: "TD",
    capacite: 25,
    disponibilite: ["mardi", "lundi", "mercredi", "samedi", "dimanche"],
  },
  {
    nom: "191",
    type: "TD",
    capacite: 30,
    disponibilite: ["samedi", "mardi", "dimanche", "jeudi", "lundi"],
  },
  {
    nom: "192",
    type: "TD",
    capacite: 32,
    disponibilite: ["mardi", "mercredi", "dimanche"],
  },
  {
    nom: "193",
    type: "TD",
    capacite: 28,
    disponibilite: ["lundi", "mercredi", "dimanche", "jeudi"],
  },
  {
    nom: "194",
    type: "TD",
    capacite: 25,
    disponibilite: ["dimanche", "mardi", "lundi", "mercredi"],
  },
  {
    nom: "195",
    type: "TD",
    capacite: 30,
    disponibilite: ["mercredi", "samedi", "dimanche"],
  },
  {
    nom: "196",
    type: "TD",
    capacite: 33,
    disponibilite: ["dimanche", "mercredi", "lundi"],
  },
  {
    nom: "197",
    type: "TD",
    capacite: 31,
    disponibilite: ["jeudi", "mardi", "mercredi", "samedi"],
  },
  {
    nom: "198",
    type: "TD",
    capacite: 32,
    disponibilite: ["samedi", "lundi", "mardi", "mercredi"],
  },
  {
    nom: "199",
    type: "TD",
    capacite: 27,
    disponibilite: ["mercredi", "mardi", "lundi"],
  },
  {
    nom: "200",
    type: "TD",
    capacite: 30,
    disponibilite: ["mardi", "mercredi", "lundi", "jeudi"],
  },
  {
    nom: "201",
    type: "TD",
    capacite: 28,
    disponibilite: ["jeudi", "mardi", "lundi", "samedi"],
  },
  {
    nom: "202",
    type: "TD",
    capacite: 25,
    disponibilite: ["jeudi", "dimanche", "mardi", "lundi", "mercredi"],
  },
  {
    nom: "203",
    type: "TD",
    capacite: 31,
    disponibilite: ["lundi", "samedi", "mardi"],
  },
  {
    nom: "204",
    type: "TD",
    capacite: 29,
    disponibilite: ["mardi", "mercredi", "lundi"],
  },
  {
    nom: "205",
    type: "TD",
    capacite: 32,
    disponibilite: ["dimanche", "mardi", "samedi", "jeudi", "mercredi"],
  },
  {
    nom: "206",
    type: "TD",
    capacite: 30,
    disponibilite: ["jeudi", "dimanche", "lundi", "samedi", "mercredi"],
  },
  {
    nom: "207",
    type: "TD",
    capacite: 33,
    disponibilite: ["samedi", "lundi", "mardi", "dimanche"],
  },
  {
    nom: "208",
    type: "TD",
    capacite: 31,
    disponibilite: ["mercredi", "lundi", "dimanche", "jeudi"],
  },
  {
    nom: "209",
    type: "TD",
    capacite: 34,
    disponibilite: ["samedi", "jeudi", "mercredi", "lundi", "mardi"],
  },
  {
    nom: "210",
    type: "TD",
    capacite: 29,
    disponibilite: ["dimanche", "jeudi", "mardi", "lundi"],
  },
  {
    nom: "211",
    type: "TD",
    capacite: 33,
    disponibilite: ["jeudi", "mardi", "samedi", "dimanche"],
  },
  {
    nom: "212",
    type: "TD",
    capacite: 35,
    disponibilite: ["dimanche", "mercredi", "samedi"],
  },
  {
    nom: "213",
    type: "TD",
    capacite: 30,
    disponibilite: ["dimanche", "jeudi", "mardi", "mercredi"],
  },
  {
    nom: "214",
    type: "TD",
    capacite: 34,
    disponibilite: ["jeudi", "mardi", "samedi", "mercredi"],
  },
  {
    nom: "215",
    type: "TD",
    capacite: 32,
    disponibilite: ["mercredi", "jeudi", "samedi"],
  },
  {
    nom: "216",
    type: "TD",
    capacite: 25,
    disponibilite: ["mercredi", "lundi", "samedi", "mardi"],
  },
  {
    nom: "217",
    type: "TD",
    capacite: 31,
    disponibilite: ["mardi", "jeudi", "mercredi", "samedi"],
  },
  {
    nom: "218",
    type: "TD",
    capacite: 25,
    disponibilite: ["jeudi", "mardi", "dimanche", "lundi"],
  },
  {
    nom: "219",
    type: "TD",
    capacite: 29,
    disponibilite: ["dimanche", "mercredi", "samedi"],
  },
  {
    nom: "220",
    type: "TD",
    capacite: 31,
    disponibilite: ["mardi", "lundi", "mercredi", "dimanche"],
  },
  {
    nom: "221",
    type: "TD",
    capacite: 53,
    disponibilite: ["jeudi", "mardi", "samedi", "mercredi"],
  },
  {
    nom: "222",
    type: "TD",
    capacite: 68,
    disponibilite: ["samedi", "lundi", "dimanche", "jeudi"],
  },
  {
    nom: "223",
    type: "TD",
    capacite: 38,
    disponibilite: ["mercredi", "lundi", "dimanche", "samedi", "mardi"],
  },
  {
    nom: "224",
    type: "TD",
    capacite: 57,
    disponibilite: ["samedi", "lundi", "mardi"],
  },
  {
    nom: "225",
    type: "TD",
    capacite: 40,
    disponibilite: ["mercredi", "jeudi", "lundi", "mardi"],
  },
  {
    nom: "226",
    type: "TD",
    capacite: 66,
    disponibilite: ["mardi", "dimanche", "jeudi", "samedi"],
  },
  {
    nom: "227",
    type: "TD",
    capacite: 70,
    disponibilite: ["mercredi", "samedi", "mardi"],
  },
  {
    nom: "228",
    type: "TD",
    capacite: 68,
    disponibilite: ["lundi", "dimanche", "mardi"],
  },
  {
    nom: "229",
    type: "TD",
    capacite: 68,
    disponibilite: ["samedi", "dimanche", "mercredi", "lundi"],
  },
  {
    nom: "230",
    type: "TD",
    capacite: 69,
    disponibilite: ["mardi", "samedi", "mercredi", "jeudi", "dimanche"],
  },
  {
    nom: "231",
    type: "TD",
    capacite: 69,
    disponibilite: ["samedi", "dimanche", "jeudi"],
  },
  {
    nom: "232",
    type: "TD",
    capacite: 55,
    disponibilite: ["samedi", "mercredi", "mardi"],
  },
  {
    nom: "233",
    type: "TD",
    capacite: 38,
    disponibilite: ["mardi", "jeudi", "samedi", "dimanche"],
  },
  {
    nom: "234",
    type: "TD",
    capacite: 51,
    disponibilite: ["lundi", "samedi", "mercredi", "mardi", "jeudi"],
  },
  {
    nom: "235",
    type: "TD",
    capacite: 44,
    disponibilite: ["mercredi", "mardi", "dimanche"],
  },
  {
    nom: "236",
    type: "TD",
    capacite: 57,
    disponibilite: ["mercredi", "mardi", "lundi", "samedi"],
  },
  {
    nom: "237",
    type: "TD",
    capacite: 52,
    disponibilite: ["mercredi", "lundi", "mardi", "jeudi", "samedi"],
  },
  {
    nom: "238",
    type: "TD",
    capacite: 58,
    disponibilite: ["jeudi", "mercredi", "samedi"],
  },
  {
    nom: "239",
    type: "TD",
    capacite: 61,
    disponibilite: ["jeudi", "mardi", "dimanche"],
  },
  {
    nom: "240",
    type: "TD",
    capacite: 52,
    disponibilite: ["samedi", "dimanche", "lundi"],
  },
  {
    nom: "241",
    type: "TD",
    capacite: 59,
    disponibilite: ["lundi", "dimanche", "jeudi", "mercredi", "mardi"],
  },
  {
    nom: "242",
    type: "TD",
    capacite: 41,
    disponibilite: ["lundi", "mardi", "samedi", "mercredi", "jeudi"],
  },
  {
    nom: "243",
    type: "TD",
    capacite: 70,
    disponibilite: ["mercredi", "dimanche", "samedi"],
  },
  {
    nom: "244",
    type: "TD",
    capacite: 39,
    disponibilite: ["jeudi", "mercredi", "lundi"],
  },
  {
    nom: "245",
    type: "TD",
    capacite: 52,
    disponibilite: ["dimanche", "jeudi", "mercredi"],
  },
  {
    nom: "246",
    type: "TD",
    capacite: 56,
    disponibilite: ["lundi", "jeudi", "mardi", "samedi", "mercredi"],
  },
  {
    nom: "247",
    type: "TD",
    capacite: 40,
    disponibilite: ["jeudi", "dimanche", "mardi", "samedi", "lundi"],
  },
  {
    nom: "248",
    type: "TD",
    capacite: 37,
    disponibilite: ["mercredi", "samedi", "mardi", "jeudi", "lundi"],
  },
  {
    nom: "249",
    type: "TD",
    capacite: 55,
    disponibilite: ["dimanche", "mardi", "mercredi", "samedi"],
  },
  {
    nom: "250",
    type: "TD",
    capacite: 57,
    disponibilite: ["samedi", "jeudi", "mercredi", "dimanche"],
  },
  {
    nom: "251",
    type: "TD",
    capacite: 69,
    disponibilite: ["jeudi", "samedi", "dimanche"],
  },
  {
    nom: "252",
    type: "TD",
    capacite: 62,
    disponibilite: ["mardi", "lundi", "samedi", "jeudi", "mercredi"],
  },
  {
    nom: "253",
    type: "TD",
    capacite: 66,
    disponibilite: ["dimanche", "samedi", "jeudi"],
  },
  {
    nom: "254",
    type: "TD",
    capacite: 59,
    disponibilite: ["mercredi", "lundi", "dimanche", "samedi", "mardi"],
  },
  {
    nom: "255",
    type: "TD",
    capacite: 57,
    disponibilite: ["mardi", "samedi", "jeudi", "dimanche", "mercredi"],
  },
  {
    nom: "256",
    type: "TD",
    capacite: 63,
    disponibilite: ["jeudi", "lundi", "samedi"],
  },
  {
    nom: "257",
    type: "TD",
    capacite: 49,
    disponibilite: ["lundi", "samedi", "mardi", "dimanche", "mercredi"],
  },
  {
    nom: "258",
    type: "TD",
    capacite: 53,
    disponibilite: ["jeudi", "samedi", "mardi", "lundi", "dimanche"],
  },
  {
    nom: "259",
    type: "TD",
    capacite: 57,
    disponibilite: ["dimanche", "samedi", "lundi", "mardi"],
  },
  {
    nom: "260",
    type: "TD",
    capacite: 51,
    disponibilite: ["samedi", "mercredi", "lundi"],
  },
  {
    nom: "261",
    type: "TD",
    capacite: 57,
    disponibilite: ["mardi", "mercredi", "dimanche", "jeudi", "samedi"],
  },
  {
    nom: "262",
    type: "TD",
    capacite: 40,
    disponibilite: ["samedi", "dimanche", "mardi"],
  },
  {
    nom: "263",
    type: "TD",
    capacite: 47,
    disponibilite: ["mercredi", "dimanche", "samedi", "lundi", "jeudi"],
  },
  {
    nom: "264",
    type: "TD",
    capacite: 55,
    disponibilite: ["dimanche", "mercredi", "mardi", "jeudi"],
  },
  {
    nom: "265",
    type: "TD",
    capacite: 45,
    disponibilite: ["jeudi", "lundi", "dimanche", "mercredi", "samedi"],
  },
  {
    nom: "266",
    type: "TD",
    capacite: 67,
    disponibilite: ["mercredi", "mardi", "jeudi", "lundi", "samedi"],
  },
  {
    nom: "267",
    type: "TD",
    capacite: 57,
    disponibilite: ["dimanche", "mercredi", "lundi", "mardi"],
  },
  {
    nom: "268",
    type: "TD",
    capacite: 64,
    disponibilite: ["mardi", "samedi", "dimanche"],
  },
  {
    nom: "269",
    type: "TD",
    capacite: 65,
    disponibilite: ["lundi", "mercredi", "jeudi", "mardi", "samedi"],
  },
  {
    nom: "270",
    type: "TD",
    capacite: 39,
    disponibilite: ["dimanche", "lundi", "samedi", "mercredi", "mardi"],
  },
  {
    nom: "271",
    type: "TD",
    capacite: 54,
    disponibilite: ["jeudi", "dimanche", "mardi", "samedi", "lundi"],
  },
  {
    nom: "272",
    type: "TD",
    capacite: 47,
    disponibilite: ["mardi", "mercredi", "dimanche"],
  },
  {
    nom: "273",
    type: "TD",
    capacite: 39,
    disponibilite: ["mercredi", "lundi", "jeudi"],
  },
  {
    nom: "274",
    type: "TD",
    capacite: 68,
    disponibilite: ["mardi", "jeudi", "mercredi"],
  },
  {
    nom: "275",
    type: "TD",
    capacite: 49,
    disponibilite: ["samedi", "dimanche", "jeudi", "mardi"],
  },
  {
    nom: "276",
    type: "TD",
    capacite: 53,
    disponibilite: ["lundi", "mardi", "samedi", "mercredi", "jeudi"],
  },
  {
    nom: "277",
    type: "TD",
    capacite: 61,
    disponibilite: ["samedi", "jeudi", "mardi", "dimanche"],
  },
  {
    nom: "278",
    type: "TD",
    capacite: 41,
    disponibilite: ["mercredi", "dimanche", "lundi", "mardi"],
  },
  {
    nom: "279",
    type: "TD",
    capacite: 50,
    disponibilite: ["mercredi", "mardi", "lundi"],
  },
  {
    nom: "280",
    type: "TD",
    capacite: 42,
    disponibilite: ["lundi", "dimanche", "jeudi", "samedi"],
  },
  {
    nom: "281",
    type: "TD",
    capacite: 39,
    disponibilite: ["dimanche", "mardi", "jeudi", "mercredi", "lundi"],
  },
  {
    nom: "282",
    type: "TD",
    capacite: 50,
    disponibilite: ["mardi", "dimanche", "lundi", "mercredi"],
  },
  {
    nom: "283",
    type: "TD",
    capacite: 68,
    disponibilite: ["dimanche", "jeudi", "mercredi", "mardi"],
  },
  {
    nom: "284",
    type: "TD",
    capacite: 63,
    disponibilite: ["mardi", "jeudi", "mercredi", "dimanche"],
  },
  {
    nom: "285",
    type: "TD",
    capacite: 64,
    disponibilite: ["mardi", "jeudi", "dimanche", "mercredi", "samedi"],
  },
  {
    nom: "286",
    type: "TD",
    capacite: 50,
    disponibilite: ["lundi", "mardi", "dimanche"],
  },
  {
    nom: "287",
    type: "TD",
    capacite: 49,
    disponibilite: ["dimanche", "jeudi", "mercredi", "lundi"],
  },
  {
    nom: "288",
    type: "TD",
    capacite: 66,
    disponibilite: ["dimanche", "jeudi", "mercredi"],
  },
  {
    nom: "289",
    type: "TD",
    capacite: 48,
    disponibilite: ["dimanche", "mercredi", "jeudi", "lundi"],
  },
  {
    nom: "290",
    type: "TD",
    capacite: 58,
    disponibilite: ["mercredi", "samedi", "lundi", "jeudi", "mardi"],
  },
  {
    nom: "291",
    type: "TD",
    capacite: 48,
    disponibilite: ["jeudi", "mardi", "lundi", "mercredi"],
  },
  {
    nom: "292",
    type: "TD",
    capacite: 37,
    disponibilite: ["mardi", "samedi", "jeudi"],
  },
  {
    nom: "293",
    type: "TD",
    capacite: 39,
    disponibilite: ["lundi", "mardi", "samedi", "jeudi"],
  },
  {
    nom: "294",
    type: "TD",
    capacite: 68,
    disponibilite: ["mardi", "lundi", "mercredi", "jeudi", "dimanche"],
  },
  {
    nom: "295",
    type: "TD",
    capacite: 37,
    disponibilite: ["mercredi", "mardi", "lundi", "jeudi"],
  },
  {
    nom: "296",
    type: "TD",
    capacite: 58,
    disponibilite: ["mardi", "lundi", "mercredi", "dimanche", "samedi"],
  },
  {
    nom: "297",
    type: "TD",
    capacite: 69,
    disponibilite: ["jeudi", "samedi", "mardi", "lundi"],
  },
  {
    nom: "298",
    type: "TD",
    capacite: 54,
    disponibilite: ["samedi", "jeudi", "dimanche", "mardi"],
  },
  {
    nom: "299",
    type: "TD",
    capacite: 54,
    disponibilite: ["mercredi", "mardi", "samedi", "jeudi"],
  },
  {
    nom: "300",
    type: "TD",
    capacite: 42,
    disponibilite: ["jeudi", "mercredi", "lundi"],
  },
  {
    nom: "301",
    type: "TD",
    capacite: 67,
    disponibilite: ["jeudi", "lundi", "mardi", "mercredi", "dimanche"],
  },
  {
    nom: "302",
    type: "TD",
    capacite: 42,
    disponibilite: ["dimanche", "mercredi", "samedi", "jeudi", "lundi"],
  },
  {
    nom: "303",
    type: "TD",
    capacite: 36,
    disponibilite: ["mardi", "lundi", "jeudi"],
  },
  {
    nom: "304",
    type: "TD",
    capacite: 70,
    disponibilite: ["jeudi", "mercredi", "samedi"],
  },
  {
    nom: "305",
    type: "TD",
    capacite: 41,
    disponibilite: ["samedi", "jeudi", "mercredi"],
  },
  {
    nom: "306",
    type: "TD",
    capacite: 68,
    disponibilite: ["samedi", "jeudi", "mardi"],
  },
  {
    nom: "307",
    type: "TD",
    capacite: 42,
    disponibilite: ["mardi", "mercredi", "samedi", "jeudi"],
  },
  {
    nom: "308",
    type: "TD",
    capacite: 68,
    disponibilite: ["jeudi", "mercredi", "dimanche", "samedi"],
  },
  {
    nom: "309",
    type: "TD",
    capacite: 68,
    disponibilite: ["jeudi", "samedi", "dimanche", "mercredi", "mardi"],
  },
  {
    nom: "310",
    type: "TD",
    capacite: 70,
    disponibilite: ["mardi", "samedi", "jeudi", "mercredi"],
  },
  {
    nom: "311",
    type: "cour",
    capacite: 80,
    disponibilite: ["mardi", "jeudi", "dimanche", "samedi"],
  },
  {
    nom: "312",
    type: "cour",
    capacite: 82,
    disponibilite: ["samedi", "lundi", "mercredi", "dimanche"],
  },
  {
    nom: "313",
    type: "cour",
    capacite: 93,
    disponibilite: ["jeudi", "mercredi", "samedi"],
  },
  {
    nom: "314",
    type: "cour",
    capacite: 97,
    disponibilite: ["mercredi", "lundi", "mardi"],
  },
  {
    nom: "315",
    type: "cour",
    capacite: 75,
    disponibilite: ["mercredi", "dimanche", "samedi", "jeudi"],
  },
  {
    nom: "316",
    type: "cour",
    capacite: 101,
    disponibilite: ["jeudi", "samedi", "mardi"],
  },
  {
    nom: "317",
    type: "cour",
    capacite: 87,
    disponibilite: ["jeudi", "samedi", "lundi"],
  },
  {
    nom: "318",
    type: "cour",
    capacite: 98,
    disponibilite: ["dimanche", "mardi", "jeudi", "samedi", "mercredi"],
  },
  {
    nom: "319",
    type: "cour",
    capacite: 98,
    disponibilite: ["mercredi", "dimanche", "jeudi"],
  },
  {
    nom: "320",
    type: "cour",
    capacite: 80,
    disponibilite: ["mardi", "lundi", "dimanche"],
  },
  {
    nom: "321",
    type: "cour",
    capacite: 82,
    disponibilite: ["lundi", "mercredi", "dimanche"],
  },
  {
    nom: "322",
    type: "cour",
    capacite: 76,
    disponibilite: ["lundi", "mercredi", "dimanche", "mardi", "samedi"],
  },
  {
    nom: "323",
    type: "cour",
    capacite: 80,
    disponibilite: ["lundi", "mardi", "samedi"],
  },
  {
    nom: "324",
    type: "cour",
    capacite: 79,
    disponibilite: ["mercredi", "dimanche", "samedi", "lundi", "mardi"],
  },
  {
    nom: "325",
    type: "cour",
    capacite: 81,
    disponibilite: ["mercredi", "samedi", "mardi"],
  },
  {
    nom: "326",
    type: "cour",
    capacite: 86,
    disponibilite: ["jeudi", "mardi", "mercredi", "lundi", "dimanche"],
  },
  {
    nom: "327",
    type: "cour",
    capacite: 92,
    disponibilite: ["jeudi", "samedi", "lundi", "dimanche", "mercredi"],
  },
  {
    nom: "328",
    type: "cour",
    capacite: 87,
    disponibilite: ["lundi", "jeudi", "dimanche", "mercredi"],
  },
  {
    nom: "329",
    type: "cour",
    capacite: 92,
    disponibilite: ["mercredi", "lundi", "mardi"],
  },
  {
    nom: "330",
    type: "cour",
    capacite: 87,
    disponibilite: ["mardi", "jeudi", "mercredi", "samedi", "dimanche"],
  },
  {
    nom: "331",
    type: "cour",
    capacite: 102,
    disponibilite: ["jeudi", "mercredi", "mardi", "dimanche", "samedi"],
  },
  {
    nom: "332",
    type: "cour",
    capacite: 102,
    disponibilite: ["jeudi", "lundi", "dimanche"],
  },
  {
    nom: "333",
    type: "cour",
    capacite: 101,
    disponibilite: ["jeudi", "lundi", "dimanche", "samedi", "mardi"],
  },
  {
    nom: "334",
    type: "cour",
    capacite: 90,
    disponibilite: ["samedi", "mercredi", "mardi", "dimanche", "jeudi"],
  },
  {
    nom: "335",
    type: "cour",
    capacite: 90,
    disponibilite: ["jeudi", "dimanche", "mardi", "lundi", "mercredi"],
  },
  {
    nom: "336",
    type: "cour",
    capacite: 102,
    disponibilite: ["mardi", "jeudi", "dimanche", "mercredi", "samedi"],
  },
  {
    nom: "337",
    type: "cour",
    capacite: 79,
    disponibilite: ["samedi", "lundi", "dimanche", "mercredi", "jeudi"],
  },
  {
    nom: "338",
    type: "cour",
    capacite: 95,
    disponibilite: ["jeudi", "lundi", "mardi", "mercredi"],
  },
  {
    nom: "339",
    type: "cour",
    capacite: 85,
    disponibilite: ["dimanche", "lundi", "mercredi", "samedi", "mardi"],
  },
  {
    nom: "340",
    type: "cour",
    capacite: 82,
    disponibilite: ["samedi", "mardi", "lundi", "mercredi", "dimanche"],
  },
  {
    nom: "341",
    type: "cour",
    capacite: 94,
    disponibilite: ["mercredi", "jeudi", "samedi", "mardi"],
  },
  {
    nom: "342",
    type: "cour",
    capacite: 85,
    disponibilite: ["dimanche", "mardi", "lundi", "mercredi", "samedi"],
  },
  {
    nom: "343",
    type: "cour",
    capacite: 74,
    disponibilite: ["mardi", "mercredi", "samedi", "lundi", "jeudi"],
  },
  {
    nom: "344",
    type: "cour",
    capacite: 96,
    disponibilite: ["mercredi", "lundi", "mardi", "jeudi", "samedi"],
  },
  {
    nom: "345",
    type: "cour",
    capacite: 85,
    disponibilite: ["mercredi", "lundi", "mardi"],
  },
  {
    nom: "346",
    type: "cour",
    capacite: 109,
    disponibilite: ["dimanche", "mardi", "lundi", "jeudi"],
  },
  {
    nom: "347",
    type: "cour",
    capacite: 92,
    disponibilite: ["lundi", "mercredi", "mardi", "samedi", "dimanche"],
  },
  {
    nom: "348",
    type: "cour",
    capacite: 104,
    disponibilite: ["mardi", "lundi", "mercredi"],
  },
  {
    nom: "349",
    type: "cour",
    capacite: 80,
    disponibilite: ["dimanche", "mercredi", "mardi"],
  },
  {
    nom: "350",
    type: "cour",
    capacite: 71,
    disponibilite: ["lundi", "jeudi", "samedi"],
  },
  {
    nom: "351",
    type: "cour",
    capacite: 82,
    disponibilite: ["lundi", "jeudi", "mercredi", "dimanche", "mardi"],
  },
  {
    nom: "352",
    type: "cour",
    capacite: 85,
    disponibilite: ["lundi", "jeudi", "dimanche", "mercredi", "samedi"],
  },
  {
    nom: "353",
    type: "cour",
    capacite: 89,
    disponibilite: ["samedi", "lundi", "jeudi", "mardi"],
  },
  {
    nom: "354",
    type: "cour",
    capacite: 94,
    disponibilite: ["samedi", "lundi", "dimanche", "mardi"],
  },
  {
    nom: "355",
    type: "cour",
    capacite: 110,
    disponibilite: ["mercredi", "samedi", "jeudi", "dimanche"],
  },
  {
    nom: "356",
    type: "cour",
    capacite: 109,
    disponibilite: ["dimanche", "samedi", "jeudi", "lundi", "mercredi"],
  },
  {
    nom: "357",
    type: "cour",
    capacite: 92,
    disponibilite: ["mardi", "jeudi", "samedi"],
  },
  {
    nom: "358",
    type: "cour",
    capacite: 75,
    disponibilite: ["mercredi", "mardi", "jeudi", "dimanche"],
  },
  {
    nom: "359",
    type: "cour",
    capacite: 81,
    disponibilite: ["mardi", "lundi", "dimanche"],
  },
  {
    nom: "360",
    type: "cour",
    capacite: 96,
    disponibilite: ["jeudi", "lundi", "mardi", "mercredi", "samedi"],
  },
  {
    nom: "361",
    type: "cour",
    capacite: 73,
    disponibilite: ["mercredi", "lundi", "dimanche", "jeudi", "mardi"],
  },
  {
    nom: "362",
    type: "cour",
    capacite: 77,
    disponibilite: ["samedi", "mercredi", "lundi", "jeudi", "mardi"],
  },
  {
    nom: "363",
    type: "cour",
    capacite: 99,
    disponibilite: ["mardi", "dimanche", "mercredi", "lundi", "samedi"],
  },
  {
    nom: "364",
    type: "cour",
    capacite: 107,
    disponibilite: ["lundi", "mardi", "dimanche", "samedi"],
  },
  {
    nom: "365",
    type: "cour",
    capacite: 96,
    disponibilite: ["lundi", "mercredi", "samedi", "jeudi", "dimanche"],
  },
  {
    nom: "366",
    type: "cour",
    capacite: 89,
    disponibilite: ["dimanche", "samedi", "mercredi", "lundi"],
  },
  {
    nom: "367",
    type: "cour",
    capacite: 90,
    disponibilite: ["mardi", "jeudi", "mercredi"],
  },
  {
    nom: "368",
    type: "cour",
    capacite: 71,
    disponibilite: ["mardi", "lundi", "mercredi", "jeudi", "samedi"],
  },
  {
    nom: "369",
    type: "cour",
    capacite: 81,
    disponibilite: ["jeudi", "dimanche", "mercredi", "samedi", "lundi"],
  },
  {
    nom: "370",
    type: "cour",
    capacite: 107,
    disponibilite: ["mercredi", "lundi", "jeudi", "samedi", "dimanche"],
  },
  {
    nom: "126",
    type: "TP",
    capacite: 39,
    disponibilite: ["mercredi", "dimanche", "lundi", "mardi"],
  },
  {
    nom: "127",
    type: "TP",
    capacite: 38,
    disponibilite: ["mercredi", "jeudi", "samedi", "mardi"],
  },
  {
    nom: "128",
    type: "TP",
    capacite: 33,
    disponibilite: ["samedi", "dimanche", "jeudi", "mercredi"],
  },
  {
    nom: "129",
    type: "TP",
    capacite: 38,
    disponibilite: ["dimanche", "mardi", "lundi", "samedi"],
  },
  {
    nom: "130",
    type: "TP",
    capacite: 39,
    disponibilite: ["samedi", "lundi", "mardi", "mercredi"],
  },
  {
    nom: "131",
    type: "TP",
    capacite: 34,
    disponibilite: ["samedi", "mercredi", "mardi"],
  },
  {
    nom: "132",
    type: "TP",
    capacite: 36,
    disponibilite: ["mercredi", "dimanche", "jeudi"],
  },
  {
    nom: "C1",
    type: "TP",
    capacite: 37,
    disponibilite: ["samedi", "jeudi", "mercredi"],
  },
  {
    nom: "C2",
    type: "TP",
    capacite: 33,
    disponibilite: ["samedi", "mardi", "mercredi"],
  },
  {
    nom: "C3",
    type: "TP",
    capacite: 33,
    disponibilite: ["lundi", "dimanche", "mercredi"],
  },
  {
    nom: "C4",
    type: "TP",
    capacite: 39,
    disponibilite: ["lundi", "dimanche", "mercredi", "samedi", "jeudi"],
  },
  {
    nom: "C5",
    type: "TP",
    capacite: 33,
    disponibilite: ["mardi", "jeudi", "mercredi"],
  },
  {
    nom: "C6",
    type: "TP",
    capacite: 35,
    disponibilite: ["jeudi", "lundi", "samedi"],
  },
  {
    nom: "C7",
    type: "TP",
    capacite: 35,
    disponibilite: ["dimanche", "lundi", "jeudi", "mardi", "mercredi"],
  },
  {
    nom: "C8",
    type: "TP",
    capacite: 35,
    disponibilite: ["lundi", "mardi", "jeudi", "samedi"],
  },
  {
    nom: "Amphi A",
    type: "cour",
    capacite: 175,
    disponibilite: ["lundi", "jeudi", "samedi"],
  },
  {
    nom: "Amphi B",
    type: "cour",
    capacite: 149,
    disponibilite: ["jeudi", "mercredi", "mardi", "lundi", "samedi"],
  },
  {
    nom: "Amphi C",
    type: "cour",
    capacite: 127,
    disponibilite: ["lundi", "samedi", "mercredi"],
  },
  {
    nom: "Amphi D",
    type: "cour",
    capacite: 145,
    disponibilite: ["mardi", "jeudi", "dimanche", "samedi", "lundi"],
  },
  {
    nom: "Amphi E",
    type: "cour",
    capacite: 128,
    disponibilite: ["dimanche", "lundi", "mercredi", "samedi", "jeudi"],
  },
  {
    nom: "Amphi F",
    type: "cour",
    capacite: 134,
    disponibilite: ["mardi", "samedi", "lundi", "mercredi"],
  },
  {
    nom: "Amphi G",
    type: "cour",
    capacite: 137,
    disponibilite: ["dimanche", "mardi", "mercredi", "samedi", "jeudi"],
  },
  {
    nom: "Amphi H",
    type: "cour",
    capacite: 173,
    disponibilite: ["mardi", "mercredi", "dimanche", "jeudi", "samedi"],
  },
  {
    nom: "Amphi I",
    type: "cour",
    capacite: 168,
    disponibilite: ["samedi", "dimanche", "lundi", "mercredi", "jeudi"],
  },
  {
    nom: "Amphi J",
    type: "cour",
    capacite: 135,
    disponibilite: ["dimanche", "mercredi", "lundi", "mardi"],
  },
  {
    nom: "Amphi K",
    type: "cour",
    capacite: 153,
    disponibilite: ["mercredi", "mardi", "samedi", "lundi", "dimanche"],
  },
  {
    nom: "Amphi L",
    type: "cour",
    capacite: 178,
    disponibilite: ["lundi", "mardi", "mercredi"],
  },
  {
    nom: "Amphi M",
    type: "cour",
    capacite: 144,
    disponibilite: ["jeudi", "lundi", "samedi", "mardi"],
  },
  {
    nom: "Amphi N",
    type: "cour",
    capacite: 180,
    disponibilite: ["mardi", "mercredi", "jeudi", "samedi", "lundi"],
  },
  {
    nom: "Amphi O",
    type: "cour",
    capacite: 143,
    disponibilite: ["mardi", "mercredi", "dimanche"],
  },
  {
    nom: "Amphi P",
    type: "cour",
    capacite: 138,
    disponibilite: ["mercredi", "jeudi", "lundi", "samedi"],
  },
  {
    nom: "Amphi Q",
    type: "cour",
    capacite: 155,
    disponibilite: ["dimanche", "mercredi", "jeudi", "mardi", "lundi"],
  },
  {
    nom: "Amphi R",
    type: "cour",
    capacite: 174,
    disponibilite: ["mercredi", "samedi", "dimanche"],
  },
  {
    nom: "Amphi S",
    type: "cour",
    capacite: 127,
    disponibilite: ["jeudi", "mercredi", "samedi", "lundi"],
  },
  {
    nom: "Amphi T",
    type: "cour",
    capacite: 142,
    disponibilite: ["jeudi", "samedi", "dimanche", "lundi", "mardi"],
  },
  {
    nom: "Amphi U",
    type: "cour",
    capacite: 178,
    disponibilite: ["dimanche", "jeudi", "samedi", "mercredi"],
  },
  {
    nom: "Amphi V",
    type: "cour",
    capacite: 176,
    disponibilite: ["mercredi", "samedi", "dimanche"],
  },
  {
    nom: "Amphi W",
    type: "cour",
    capacite: 128,
    disponibilite: ["lundi", "samedi", "dimanche", "jeudi", "mercredi"],
  },
  {
    nom: "Amphi X",
    type: "cour",
    capacite: 144,
    disponibilite: ["jeudi", "dimanche", "samedi", "mercredi", "lundi"],
  },
  {
    nom: "Amphi Y",
    type: "cour",
    capacite: 124,
    disponibilite: ["samedi", "jeudi", "dimanche"],
  },
  {
    nom: "Amphi Z",
    type: "cour",
    capacite: 127,
    disponibilite: ["mardi", "mercredi", "dimanche"],
  },
  {
    nom: "R1",
    type: "cour",
    capacite: 101,
    disponibilite: ["samedi", "mercredi", "mardi"],
  },
  {
    nom: "E1",
    type: "cour",
    capacite: 107,
    disponibilite: ["samedi", "mercredi", "mardi", "lundi", "dimanche"],
  },
  {
    nom: "D1",
    type: "cour",
    capacite: 92,
    disponibilite: ["mardi", "samedi", "dimanche", "lundi", "mercredi"],
  },
  {
    nom: "R2",
    type: "cour",
    capacite: 91,
    disponibilite: ["mardi", "samedi", "mercredi", "lundi"],
  },
  {
    nom: "E2",
    type: "cour",
    capacite: 103,
    disponibilite: ["dimanche", "samedi", "lundi", "jeudi"],
  },
  {
    nom: "D2",
    type: "cour",
    capacite: 103,
    disponibilite: ["mercredi", "jeudi", "samedi", "dimanche"],
  },
  {
    nom: "R3",
    type: "cour",
    capacite: 110,
    disponibilite: ["jeudi", "samedi", "lundi", "dimanche"],
  },
  {
    nom: "E3",
    type: "cour",
    capacite: 93,
    disponibilite: ["mercredi", "jeudi", "mardi", "samedi", "dimanche"],
  },
  {
    nom: "D3",
    type: "cour",
    capacite: 111,
    disponibilite: ["mercredi", "dimanche", "mardi", "lundi"],
  },
  {
    nom: "R4",
    type: "cour",
    capacite: 91,
    disponibilite: ["mercredi", "jeudi", "samedi"],
  },
  {
    nom: "E4",
    type: "cour",
    capacite: 101,
    disponibilite: ["dimanche", "samedi", "mardi", "jeudi", "mercredi"],
  },
  {
    nom: "D4",
    type: "cour",
    capacite: 95,
    disponibilite: ["dimanche", "mardi", "jeudi"],
  },
  {
    nom: "R5",
    type: "cour",
    capacite: 111,
    disponibilite: ["samedi", "lundi", "dimanche", "mardi"],
  },
  {
    nom: "E5",
    type: "cour",
    capacite: 100,
    disponibilite: ["jeudi", "samedi", "lundi", "mercredi"],
  },
  {
    nom: "D5",
    type: "cour",
    capacite: 98,
    disponibilite: ["mardi", "jeudi", "dimanche", "mercredi"],
  },
  {
    nom: "R6",
    type: "cour",
    capacite: 113,
    disponibilite: ["lundi", "mardi", "dimanche", "samedi", "jeudi"],
  },
  {
    nom: "E6",
    type: "cour",
    capacite: 108,
    disponibilite: ["dimanche", "mercredi", "samedi", "lundi"],
  },
  {
    nom: "D6",
    type: "cour",
    capacite: 105,
    disponibilite: ["dimanche", "lundi", "mercredi", "mardi"],
  },
  {
    nom: "R7",
    type: "cour",
    capacite: 103,
    disponibilite: ["mercredi", "dimanche", "samedi", "jeudi", "mardi"],
  },
  {
    nom: "E7",
    type: "cour",
    capacite: 99,
    disponibilite: ["jeudi", "dimanche", "mercredi", "samedi", "lundi"],
  },
  {
    nom: "D7",
    type: "cour",
    capacite: 107,
    disponibilite: ["lundi", "dimanche", "mardi", "mercredi"],
  },
  {
    nom: "R8",
    type: "cour",
    capacite: 93,
    disponibilite: ["lundi", "mercredi", "dimanche", "samedi"],
  },
  {
    nom: "E8",
    type: "cour",
    capacite: 114,
    disponibilite: ["mardi", "lundi", "jeudi"],
  },
  {
    nom: "D8",
    type: "cour",
    capacite: 108,
    disponibilite: ["dimanche", "lundi", "samedi", "jeudi", "mercredi"],
  },
  {
    nom: "R9",
    type: "cour",
    capacite: 103,
    disponibilite: ["samedi", "mardi", "dimanche"],
  },
  {
    nom: "E9",
    type: "cour",
    capacite: 113,
    disponibilite: ["samedi", "dimanche", "mercredi"],
  },
  {
    nom: "D9",
    type: "cour",
    capacite: 101,
    disponibilite: ["samedi", "mardi", "dimanche"],
  },
];
