export const teacherData = [
  {
    nom: "Attar",
    prenom: "Zara",
    gender: "female",
    email: "zara.attar@example.com",
    "numero de telephone": "0517896723",
    "Date de naissance": "1990-09-10",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mercredi", "samedi", "mardi"],
    modules: [
      "reseaux",
      "Théorie des jeux",
      "Administration et Gestion des grilles de calcul",
      "Programmation et sûreté des systèmes répartis",
    ],
  },
  {
    nom: "Hassaine",
    prenom: "Adem",
    gender: "male",
    email: "adem.hassaine@example.com",
    "numero de telephone": "0685648785",
    "Date de naissance": "1982-07-17",
    grade: "Doctorant",
    availability_prof: ["dimanche", "samedi", "mercredi"],
    modules: [
      "Stratégie de sécurité pour l’aide à la décision",
      "term",
      "anglais",
    ],
  },
  {
    nom: "Benrahou",
    prenom: "Mahdi",
    gender: "male",
    email: "mahdi.benrahou@example.com",
    "numero de telephone": "0698624378",
    "Date de naissance": "1984-03-29",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["mardi", "mercredi", "samedi", "dimanche"],
    modules: [
      "Calcul parallèle et grilles de calcul",
      "programmation web avancee",
      "poo",
    ],
  },
  {
    nom: "Ba",
    prenom: "Sara",
    gender: "female",
    email: "sara.ba@example.com",
    "numero de telephone": "0591167444",
    "Date de naissance": "1988-12-20",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["mercredi", "lundi", "jeudi", "dimanche"],
    modules: [
      "Représentation de connaissances et raisonnement 2",
      "anglais",
      "proba 2",
      "Concepts Avancés du Génie Logiciel",
    ],
  },
  {
    nom: "Boussaid",
    prenom: "Elias",
    gender: "male",
    email: "elias.boussaid@example.com",
    "numero de telephone": "0673903658",
    "Date de naissance": "1991-06-02",
    grade: "Professeur",
    availability_prof: ["mercredi", "jeudi", "samedi", "lundi"],
    modules: ["Système d’exploitation 2", "Programmation réseau", "algebre"],
  },
  {
    nom: "Bouhaddi",
    prenom: "Mariam",
    gender: "female",
    email: "mariam.bouhaddi@example.com",
    "numero de telephone": "0715137453",
    "Date de naissance": "1998-03-02",
    grade: "Doctorant",
    availability_prof: ["jeudi", "mercredi", "dimanche", "mardi"],
    modules: [
      "sfsd",
      "ACP: Architecture et Calcul Parallèle",
      "anglais",
      "Complexité algorithmique",
    ],
  },
  {
    nom: "Houari",
    prenom: "Afif",
    gender: "male",
    email: "afif.houari@example.com",
    "numero de telephone": "0688783940",
    "Date de naissance": "1992-09-06",
    grade: "Maître Assistant Classe A",
    availability_prof: ["jeudi", "samedi"],
    modules: [
      "analyse",
      "Sécurité système avancée",
      "Méthodologie et Processus de Développement de Logiciels",
    ],
  },
  {
    nom: "Boulahia",
    prenom: "Shahid",
    gender: "male",
    email: "shahid.boulahia@example.com",
    "numero de telephone": "0714400413",
    "Date de naissance": "1980-08-29",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["samedi", "mardi", "mercredi", "lundi"],
    modules: [
      "Gestion de Projet de Développement de Logiciels",
      "anglais",
      "Systèmes d’exploitation distribués",
    ],
  },
  {
    nom: "Boujemaa",
    prenom: "Daoud",
    gender: "male",
    email: "daoud.boujemaa@example.com",
    "numero de telephone": "0713047583",
    "Date de naissance": "1989-09-01",
    grade: "Doctorant",
    availability_prof: ["jeudi", "mardi", "lundi", "mercredi"],
    modules: [
      "Introduction aux systèmes d’exploitation 1",
      "Théorie des jeux",
      "anglais",
    ],
  },
  {
    nom: "Boujemaa",
    prenom: "Abdallah",
    gender: "male",
    email: "abdallah.boujemaa@example.com",
    "numero de telephone": "0740579372",
    "Date de naissance": "1984-11-14",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["samedi", "mardi"],
    modules: [
      "term",
      "Visualisation de données",
      "Traitement automatique du langage naturel",
    ],
  },
  {
    nom: "Cherif",
    prenom: "Brahim",
    gender: "male",
    email: "brahim.cherif@example.com",
    "numero de telephone": "0561802920",
    "Date de naissance": "1979-07-26",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["mercredi", "lundi", "dimanche"],
    modules: [
      "Modélisation et évaluation des performances des systèmes",
      "anglais",
      "strm1",
      "TBI-SIG : Technologies Business Intelligence",
    ],
  },
  {
    nom: "Daoud",
    prenom: "Abdelkader",
    gender: "male",
    email: "abdelkader.daoud@example.com",
    "numero de telephone": "0743730472",
    "Date de naissance": "1966-06-14",
    grade: "Maître Assistant Classe B",
    availability_prof: ["samedi", "dimanche"],
    modules: ["Complexité algorithmique", "anglais", "Synthèses d’images"],
  },
  {
    nom: "Benghalia",
    prenom: "Ziyad",
    gender: "male",
    email: "ziyad.benghalia@example.com",
    "numero de telephone": "0718924446",
    "Date de naissance": "1970-10-22",
    grade: "Doctorant",
    availability_prof: ["samedi", "mercredi"],
    modules: [
      "ACP: Architecture et Calcul Parallèle",
      "BIOMATH : Biomathématique",
      "Compilation : génération du code et optimisation",
      "Méthodes d’optimisation",
    ],
  },
  {
    nom: "Chalhoub",
    prenom: "Nadia",
    gender: "female",
    email: "nadia.chalhoub@example.com",
    "numero de telephone": "0613726916",
    "Date de naissance": "1991-08-17",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mercredi", "dimanche", "samedi"],
    modules: [
      "Génie Logiciel 2",
      "Imagerie Médicale et Parallélisme",
      "BIOGEN : Bioinfo et Génomique",
      "Construction d’applications réparties",
    ],
  },
  {
    nom: "Hamdi",
    prenom: "Amina",
    gender: "female",
    email: "amina.hamdi@example.com",
    "numero de telephone": "0557382563",
    "Date de naissance": "1998-09-27",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mardi", "jeudi", "lundi"],
    modules: [
      "Systèmes d’Information Coopératifs",
      "anglais",
      "BIOSTAT : Biostatistique",
      "BIOGEN : Bioinfo et Génomique",
    ],
  },
  {
    nom: "Ghannouchi",
    prenom: "Tarek",
    gender: "male",
    email: "tarek.ghannouchi@example.com",
    "numero de telephone": "0753844231",
    "Date de naissance": "1997-10-31",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["samedi", "mercredi", "lundi", "mardi"],
    modules: [
      "Audit de sécurité",
      "Algorithmique et complexité",
      "Aspects juridiques dans la sécurité informatique",
      "Sécurité système avancée",
    ],
  },
  {
    nom: "Hmida",
    prenom: "Nadia",
    gender: "female",
    email: "nadia.hmida@example.com",
    "numero de telephone": "0535988679",
    "Date de naissance": "1976-09-03",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mardi", "jeudi", "mercredi"],
    modules: [
      "Vision artificielle",
      "Mathématiques appliquées (Analyse numérique)",
      "strm1",
    ],
  },
  {
    nom: "Hamouda",
    prenom: "Farah",
    gender: "female",
    email: "farah.hamouda@example.com",
    "numero de telephone": "0675895807",
    "Date de naissance": "1998-08-12",
    grade: "Doctorant",
    availability_prof: ["lundi", "mercredi", "dimanche", "mardi"],
    modules: [
      "Techniques de modélisation en traitement du signal",
      "anglais",
      "BSD : Biométrie et Sécurisation de Données",
      "anglais",
    ],
  },
  {
    nom: "Arar",
    prenom: "Aïcha",
    gender: "female",
    email: "aïcha.arar@example.com",
    "numero de telephone": "0692169083",
    "Date de naissance": "1975-03-09",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["samedi", "dimanche"],
    modules: [
      "Théorie des jeux",
      "Réseaux Mobiles",
      "Programmation et sûreté des systèmes répartis",
      "Bureautique et Web",
    ],
  },
  {
    nom: "Chahine",
    prenom: "Bilal",
    gender: "male",
    email: "bilal.chahine@example.com",
    "numero de telephone": "0717086750",
    "Date de naissance": "1991-07-23",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["dimanche", "jeudi"],
    modules: [
      "FD2: Fouille de Données2",
      "BIOGEN : Bioinfo et Génomique",
      "Méthodes pratiques et outils de détection d’intrusions",
      "GPR : Gestion de Projet",
    ],
  },
  {
    nom: "Hmida",
    prenom: "Idriss",
    gender: "male",
    email: "idriss.hmida@example.com",
    "numero de telephone": "0575584987",
    "Date de naissance": "1967-10-07",
    grade: "Maître Assistant Classe A",
    availability_prof: ["dimanche", "mardi", "lundi"],
    modules: [
      "Transmissions réseaux et codage d’information",
      "modelisation et simulation",
      "anglais",
      "compilation",
    ],
  },
  {
    nom: "Chakir",
    prenom: "Abderrahmane",
    gender: "male",
    email: "abderrahmane.chakir@example.com",
    "numero de telephone": "0755999513",
    "Date de naissance": "1972-09-07",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["mercredi", "lundi"],
    modules: [
      "Visualisation de données",
      "Construction de systèmes Parallèles",
      "modelisation et simulation",
      "Assurance Qualité des Logiciels",
    ],
  },
  {
    nom: "Boudoukhane",
    prenom: "Ayman",
    gender: "male",
    email: "ayman.boudoukhane@example.com",
    "numero de telephone": "0682319977",
    "Date de naissance": "1996-02-20",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["mercredi", "jeudi", "dimanche", "mardi"],
    modules: [
      "Architectures Avancées",
      "Construction d’applications réparties",
      "anglais",
    ],
  },
  {
    nom: "Boulahia",
    prenom: "Ameen",
    gender: "male",
    email: "ameen.boulahia@example.com",
    "numero de telephone": "0513199387",
    "Date de naissance": "1996-07-22",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["dimanche", "mardi", "lundi", "samedi"],
    modules: ["Gestion de Projets de Logiciels", "algebre 3", "anglais"],
  },
  {
    nom: "Hanafi",
    prenom: "Bilal",
    gender: "male",
    email: "bilal.hanafi@example.com",
    "numero de telephone": "0528327821",
    "Date de naissance": "1985-08-20",
    grade: "Professeur",
    availability_prof: ["dimanche", "mercredi"],
    modules: [
      "anglais",
      "reseaux",
      "Méthodologie et Processus de Développement de Logiciels",
      "MCA: Méthodes Conceptuelles d’Analyse",
    ],
  },
  {
    nom: "Hammoud",
    prenom: "Abdelrahim",
    gender: "male",
    email: "abdelrahim.hammoud@example.com",
    "numero de telephone": "0668536850",
    "Date de naissance": "1968-11-04",
    grade: "Maître Assistant Classe A",
    availability_prof: ["mercredi", "samedi", "lundi", "dimanche"],
    modules: [
      "BIOSTAT : Biostatistique",
      "Méthodologie et Processus de Développement de Logiciels",
      "analyse",
    ],
  },
  {
    nom: "Chafik",
    prenom: "Dounia",
    gender: "female",
    email: "dounia.chafik@example.com",
    "numero de telephone": "0661485934",
    "Date de naissance": "1968-03-07",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mardi", "lundi", "mercredi", "dimanche"],
    modules: [
      "Utilisation et administration des systèmes d’exploitation",
      "Gestion de Projets de Logiciels",
      "Programmation et sûreté des systèmes répartis",
      "logique",
    ],
  },
  {
    nom: "Benghalia",
    prenom: "Jamal",
    gender: "male",
    email: "jamal.benghalia@example.com",
    "numero de telephone": "0777289015",
    "Date de naissance": "1993-01-25",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["lundi", "dimanche", "mardi"],
    modules: [
      "Arithmétique modulaire",
      "Gestion de Projets de Logiciels",
      "Gestion de projet",
      "TBI-SIG : Technologies Business Intelligence",
    ],
  },
  {
    nom: "Belkacem",
    prenom: "Abderahman",
    gender: "male",
    email: "abderahman.belkacem@example.com",
    "numero de telephone": "0587815405",
    "Date de naissance": "1974-11-30",
    grade: "Maître Assistant Classe A",
    availability_prof: ["samedi", "mercredi"],
    modules: [
      "anadiss ( Analyse discriminante et segmentation )",
      "Méthodes d’optimisation",
      "Programmation réseau",
    ],
  },
  {
    nom: "Boumedienne",
    prenom: "Fouad",
    gender: "male",
    email: "fouad.boumedienne@example.com",
    "numero de telephone": "0741566420",
    "Date de naissance": "1964-03-22",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["mardi", "jeudi", "samedi"],
    modules: [
      "Bureautique et Web",
      "Electronique analogique",
      "anglais",
      "Bases de Données 2",
    ],
  },
  {
    nom: "Hadjadj",
    prenom: "Ghada",
    gender: "female",
    email: "ghada.hadjadj@example.com",
    "numero de telephone": "0557130147",
    "Date de naissance": "1987-11-02",
    grade: "Doctorant",
    availability_prof: ["mercredi", "lundi", "dimanche", "jeudi"],
    modules: [
      "anglais",
      "proba",
      "TBI-SIG : Technologies Business Intelligence",
      "Modélisation des systèmes communicants",
    ],
  },
  {
    nom: "Benmoussa",
    prenom: "Shahid",
    gender: "male",
    email: "shahid.benmoussa@example.com",
    "numero de telephone": "0768383590",
    "Date de naissance": "1974-05-30",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mercredi", "jeudi", "dimanche"],
    modules: [
      "Algorithmique et complexité",
      "anadiss ( Analyse discriminante et segmentation )",
      "Introduction à la sécurité informatique",
      "Génie Logiciel et POO",
    ],
  },
  {
    nom: "Hafsi",
    prenom: "Abdelkader",
    gender: "male",
    email: "abdelkader.hafsi@example.com",
    "numero de telephone": "0745539196",
    "Date de naissance": "1986-09-25",
    grade: "Maître Assistant Classe B",
    availability_prof: ["jeudi", "mardi"],
    modules: [
      "BDABD : Bases de Données Avancées et Big Data",
      "Vision artificielle",
      "Système d’exploitation 2",
      "Systèmes Décisionnels et Entrepôts",
    ],
  },
  {
    nom: "Bouchemal",
    prenom: "Yasmina",
    gender: "female",
    email: "yasmina.bouchemal@example.com",
    "numero de telephone": "0742845520",
    "Date de naissance": "1995-04-27",
    grade: "Maître Assistant Classe A",
    availability_prof: ["jeudi", "lundi"],
    modules: [
      "Méthodes pratiques et outils de détection d’intrusions",
      "Gestion de projet",
      "VDRA: Visualisation de Données et réalité Augmentée",
    ],
  },
  {
    nom: "Cherif",
    prenom: "Ahmad",
    gender: "male",
    email: "ahmad.cherif@example.com",
    "numero de telephone": "0653311614",
    "Date de naissance": "1989-12-04",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["lundi", "mercredi", "dimanche", "samedi"],
    modules: [
      "Utilisation et administration des systèmes d’exploitation",
      "Architecture des Bases de données",
      "anglais",
    ],
  },
  {
    nom: "Boussaid",
    prenom: "Rashid",
    gender: "male",
    email: "rashid.boussaid@example.com",
    "numero de telephone": "0740534672",
    "Date de naissance": "1965-01-21",
    grade: "Professeur",
    availability_prof: ["samedi", "dimanche", "mardi"],
    modules: [
      "ACP: Architecture et Calcul Parallèle",
      "SPS : Système et Programmation de Scripts",
      "strm1",
    ],
  },
  {
    nom: "Fares",
    prenom: "Khalil",
    gender: "male",
    email: "khalil.fares@example.com",
    "numero de telephone": "0792684056",
    "Date de naissance": "1971-06-17",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["mardi", "samedi", "mercredi"],
    modules: [
      "reseaux",
      "Entreprenariat",
      "algo 1",
      "Sécurité et contrôle du trafic réseau",
    ],
  },
  {
    nom: "Alami",
    prenom: "Nasreen",
    gender: "female",
    email: "nasreen.alami@example.com",
    "numero de telephone": "0780159549",
    "Date de naissance": "1974-01-06",
    grade: "Doctorant",
    availability_prof: ["mercredi", "lundi"],
    modules: [
      "Systèmes d’Information Coopératifs",
      "Techniques de modélisation et de traitement en mécanique des fluides",
      "Modélisation des systèmes communicants",
    ],
  },
  {
    nom: "Abid",
    prenom: "Ahmad",
    gender: "male",
    email: "ahmad.abid@example.com",
    "numero de telephone": "0545110165",
    "Date de naissance": "1984-02-01",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["dimanche", "lundi", "jeudi", "samedi"],
    modules: [
      "Théorie des jeux",
      "Communication Multimédia",
      "anglais",
      "Veille technologique et Bases de données avancées",
    ],
  },
  {
    nom: "Chakir",
    prenom: "Dounia",
    gender: "female",
    email: "dounia.chakir@example.com",
    "numero de telephone": "0795907681",
    "Date de naissance": "1965-12-26",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["jeudi", "dimanche", "samedi", "mercredi"],
    modules: [
      "physique",
      "Recherche d’information",
      "Théorie des jeux",
      "Systèmes d’exploitation distribués",
    ],
  },
  {
    nom: "Boumedienne",
    prenom: "Wahid",
    gender: "male",
    email: "wahid.boumedienne@example.com",
    "numero de telephone": "0636934290",
    "Date de naissance": "1969-08-04",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["samedi", "jeudi"],
    modules: ["anglais", "option", "anglais", "BIOGEN : Bioinfo et Génomique"],
  },
  {
    nom: "Arab",
    prenom: "Nasim",
    gender: "male",
    email: "nasim.arab@example.com",
    "numero de telephone": "0795875186",
    "Date de naissance": "1990-04-20",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mercredi", "mardi"],
    modules: [
      "Réseaux et communication sans fil",
      "anglais",
      "Architectures des réseaux informatiques",
      "anglais",
    ],
  },
  {
    nom: "Boulahia",
    prenom: "Nawal",
    gender: "female",
    email: "nawal.boulahia@example.com",
    "numero de telephone": "0622705603",
    "Date de naissance": "1968-12-28",
    grade: "Maître Assistant Classe A",
    availability_prof: ["jeudi", "mercredi", "lundi"],
    modules: [
      "Architectures Avancées",
      "Traitement automatique du langage naturel",
      "Complexité algorithmique",
      "BIOSTAT : Biostatistique",
    ],
  },
  {
    nom: "Afifi",
    prenom: "Selma",
    gender: "female",
    email: "selma.afifi@example.com",
    "numero de telephone": "0773328878",
    "Date de naissance": "1988-08-27",
    grade: "Professeur",
    availability_prof: ["lundi", "samedi", "mardi"],
    modules: [
      "Gestion de Projet de Développement de Logiciels",
      "Représentation de connaissances et raisonnement",
      "Mathématiques appliquées (Analyse numérique)",
    ],
  },
  {
    nom: "Harb",
    prenom: "Habib",
    gender: "male",
    email: "habib.harb@example.com",
    "numero de telephone": "0633958645",
    "Date de naissance": "1997-07-01",
    grade: "Professeur",
    availability_prof: ["jeudi", "mercredi", "lundi"],
    modules: [
      "Modélisation et Evaluation de Performances des Systèmes",
      "Calcul Embarqué",
      "Architectures Avancées",
    ],
  },
  {
    nom: "Assaf",
    prenom: "Jamal",
    gender: "male",
    email: "jamal.assaf@example.com",
    "numero de telephone": "0628812549",
    "Date de naissance": "1995-11-23",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["dimanche", "samedi", "mardi"],
    modules: ["Gestion de projet", "anglais", "algebre"],
  },
  {
    nom: "Hattab",
    prenom: "Sahar",
    gender: "female",
    email: "sahar.hattab@example.com",
    "numero de telephone": "0755054172",
    "Date de naissance": "1989-08-10",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["lundi", "samedi", "mardi"],
    modules: [
      "Introduction aux systèmes d’exploitation 1",
      "Data Mining",
      "Architecture et administration des réseaux",
    ],
  },
  {
    nom: "Boucif",
    prenom: "Nawal",
    gender: "female",
    email: "nawal.boucif@example.com",
    "numero de telephone": "0749629428",
    "Date de naissance": "1968-07-15",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["samedi", "jeudi", "mardi"],
    modules: [
      "Traitement automatique du langage naturel",
      "Bases de Données 2",
      "Théorie des jeux",
    ],
  },
  {
    nom: "Ghaleb",
    prenom: "Tarek",
    gender: "male",
    email: "tarek.ghaleb@example.com",
    "numero de telephone": "0665348496",
    "Date de naissance": "1992-05-08",
    grade: "Maître Assistant Classe B",
    availability_prof: ["jeudi", "lundi"],
    modules: [
      "Assurance Qualité des Logiciels",
      "Sécurité applicative",
      "strm",
    ],
  },
  {
    nom: "Belkacem",
    prenom: "Tarek",
    gender: "male",
    email: "tarek.belkacem@example.com",
    "numero de telephone": "0690435382",
    "Date de naissance": "1962-09-02",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["lundi", "jeudi"],
    modules: ["BIOGEN : Bioinfo et Génomique", "compilation", "anglais"],
  },
  {
    nom: "Bahri",
    prenom: "Abid",
    gender: "male",
    email: "abid.bahri@example.com",
    "numero de telephone": "0574668837",
    "Date de naissance": "1975-10-19",
    grade: "Maître Assistant Classe B",
    availability_prof: ["jeudi", "samedi", "mardi", "lundi"],
    modules: ["archi 2", "physique", "Veille Technologie"],
  },
  {
    nom: "Boudjema",
    prenom: "Fouad",
    gender: "male",
    email: "fouad.boudjema@example.com",
    "numero de telephone": "0757254936",
    "Date de naissance": "1974-09-16",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["mercredi", "jeudi", "dimanche", "samedi"],
    modules: ["anglais", "Architecture et Administration de SGBD", "analyse 3"],
  },
  {
    nom: "Hamdan",
    prenom: "Tala",
    gender: "female",
    email: "tala.hamdan@example.com",
    "numero de telephone": "0537087544",
    "Date de naissance": "1995-09-30",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mardi", "mercredi"],
    modules: [
      "Calcul parallèle et grilles de calcul",
      "Système d’exploitation 2",
      "Gestion de projet",
    ],
  },
  {
    nom: "Ech",
    prenom: "Zainab",
    gender: "female",
    email: "zainab.ech@example.com",
    "numero de telephone": "0793235950",
    "Date de naissance": "1980-09-23",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["dimanche", "mardi"],
    modules: [
      "Gestion de Projets de Logiciels",
      "Architectures Avancées",
      "Data Mining",
    ],
  },
  {
    nom: "Chalhoub",
    prenom: "Shadi",
    gender: "male",
    email: "shadi.chalhoub@example.com",
    "numero de telephone": "0564223047",
    "Date de naissance": "1995-08-28",
    grade: "Professeur",
    availability_prof: ["mardi", "jeudi"],
    modules: [
      "archi 1",
      "SOLO : Solveurs pour l’optimisation",
      "Architecture et Administration de SGBD",
    ],
  },
  {
    nom: "Achour",
    prenom: "Mahdi",
    gender: "male",
    email: "mahdi.achour@example.com",
    "numero de telephone": "0638574185",
    "Date de naissance": "1997-03-16",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mercredi", "samedi", "mardi"],
    modules: [
      "Systèmes d’exploitation",
      "MCA: Méthodes Conceptuelles d’Analyse",
      "Optimisation linéaire (option)",
      "algebre 3",
    ],
  },
  {
    nom: "Benghalia",
    prenom: "Idriss",
    gender: "male",
    email: "idriss.benghalia@example.com",
    "numero de telephone": "0783135588",
    "Date de naissance": "1980-03-30",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["mardi", "samedi"],
    modules: [
      "Data Mining",
      "anglais",
      "FD2: Fouille de Données2",
      "Audit de sécurité",
    ],
  },
  {
    nom: "Hatem",
    prenom: "Nasim",
    gender: "male",
    email: "nasim.hatem@example.com",
    "numero de telephone": "0787510090",
    "Date de naissance": "1965-03-31",
    grade: "Professeur",
    availability_prof: ["mardi", "samedi", "jeudi", "dimanche"],
    modules: [
      "Introduction à la sécurité informatique",
      "Architectures des réseaux informatiques",
      "Entreprenariat",
    ],
  },
  {
    nom: "Chakir",
    prenom: "Zainab",
    gender: "female",
    email: "zainab.chakir@example.com",
    "numero de telephone": "0521105970",
    "Date de naissance": "1992-02-29",
    grade: "Professeur",
    availability_prof: ["dimanche", "jeudi", "mardi"],
    modules: [
      "Résolution de problèmes",
      "Gestion de Projet de Développement de Logiciels",
      "Réseaux sans fil",
      "archi 1",
    ],
  },
  {
    nom: "Bougara",
    prenom: "Zineb",
    gender: "female",
    email: "zineb.bougara@example.com",
    "numero de telephone": "0636490350",
    "Date de naissance": "1980-05-10",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["samedi", "lundi", "jeudi"],
    modules: [
      "anglais",
      "Synthèses d’images",
      "Architecture et Administration de bases de Données",
    ],
  },
  {
    nom: "Belkhadem",
    prenom: "Hamza",
    gender: "male",
    email: "hamza.belkhadem@example.com",
    "numero de telephone": "0746820568",
    "Date de naissance": "1991-12-07",
    grade: "Doctorant",
    availability_prof: ["lundi", "mercredi", "dimanche", "samedi"],
    modules: [
      "Systèmes d’exploitation Mobiles",
      "Vision artificielle",
      "Réseaux sans fil",
      "Sécurité système avancée",
    ],
  },
  {
    nom: "Hadj",
    prenom: "Elyes",
    gender: "male",
    email: "elyes.hadj@example.com",
    "numero de telephone": "0546926638",
    "Date de naissance": "1993-07-02",
    grade: "Doctorant",
    availability_prof: ["mercredi", "mardi", "jeudi", "dimanche"],
    modules: [
      "Théorie de l’ordonnancement",
      "Programmation Web",
      "modelisation et simulation",
      "Techniques de modélisation et de traitement en mécanique des fluides",
    ],
  },
  {
    nom: "El",
    prenom: "Yasmina",
    gender: "female",
    email: "yasmina.el@example.com",
    "numero de telephone": "0693555355",
    "Date de naissance": "1995-04-19",
    grade: "Maître Assistant Classe B",
    availability_prof: ["lundi", "dimanche", "mercredi"],
    modules: [
      "Mathématiques appliquées (Analyse numérique)",
      "Algorithmique et complexité",
      "Systèmes d’exploitation distribués",
    ],
  },
  {
    nom: "Benali",
    prenom: "Mansour",
    gender: "male",
    email: "mansour.benali@example.com",
    "numero de telephone": "0646363937",
    "Date de naissance": "1982-09-22",
    grade: "Maître Assistant Classe A",
    availability_prof: ["mardi", "jeudi", "samedi", "lundi"],
    modules: [
      "Programmation et sûreté des systèmes répartis",
      "anglais",
      "Bureautique et Web",
      "Théorie de l’ordonnancement",
    ],
  },
  {
    nom: "Chabane",
    prenom: "Samira",
    gender: "female",
    email: "samira.chabane@example.com",
    "numero de telephone": "0582074294",
    "Date de naissance": "1984-10-10",
    grade: "Professeur",
    availability_prof: ["mercredi", "lundi", "samedi", "mardi"],
    modules: [
      "reseaux",
      "Transmissions réseaux et codage d’information",
      "Systèmes d’exploitation distribués",
      "BIOSTAT : Biostatistique",
    ],
  },
  {
    nom: "Hajj",
    prenom: "Ayoub",
    gender: "male",
    email: "ayoub.hajj@example.com",
    "numero de telephone": "0754560743",
    "Date de naissance": "1962-08-06",
    grade: "Maître Assistant Classe B",
    availability_prof: ["jeudi", "dimanche", "mercredi"],
    modules: [
      "Systèmes de Télécom. et interopérabilité des réseaux",
      "Méthodes d’optimisation",
      "anglais",
    ],
  },
  {
    nom: "Boujemaa",
    prenom: "Sabrina",
    gender: "female",
    email: "sabrina.boujemaa@example.com",
    "numero de telephone": "0692907511",
    "Date de naissance": "1970-11-25",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mercredi", "dimanche", "lundi", "mardi"],
    modules: [
      "Résolution de problèmes",
      "Veille Technologie",
      "Programmation et sûreté des systèmes répartis",
    ],
  },
  {
    nom: "Boudoukhane",
    prenom: "Brahim",
    gender: "male",
    email: "brahim.boudoukhane@example.com",
    "numero de telephone": "0727023937",
    "Date de naissance": "1978-09-25",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["dimanche", "samedi", "mardi", "jeudi"],
    modules: [
      "compilation",
      "Mathématiques appliquées (Analyse numérique)",
      "Electronique analogique",
      "anglais",
    ],
  },
  {
    nom: "Bounoua",
    prenom: "Fouad",
    gender: "male",
    email: "fouad.bounoua@example.com",
    "numero de telephone": "0756115867",
    "Date de naissance": "1986-11-25",
    grade: "Doctorant",
    availability_prof: ["dimanche", "lundi"],
    modules: [
      "logique",
      "Modélisation et évaluation des performances des systèmes",
      "TBI-SIG : Technologies Business Intelligence",
      "Techniques de modélisation et de traitement en mécanique des fluides",
    ],
  },
  {
    nom: "Hanafi",
    prenom: "Anas",
    gender: "male",
    email: "anas.hanafi@example.com",
    "numero de telephone": "0586486964",
    "Date de naissance": "1971-09-19",
    grade: "Maître Assistant Classe B",
    availability_prof: ["jeudi", "mardi"],
    modules: [
      "option",
      "Complexité algorithmique",
      "Sécurité applicative",
      "Théorie de l’info. caractérisation de la transmission",
    ],
  },
  {
    nom: "Afifi",
    prenom: "Malika",
    gender: "female",
    email: "malika.afifi@example.com",
    "numero de telephone": "0730847399",
    "Date de naissance": "1970-01-19",
    grade: "Doctorant",
    availability_prof: ["lundi", "jeudi", "mardi"],
    modules: [
      "Représentation de connaissances et raisonnement",
      "algo 3",
      "VDRA: Visualisation de Données et réalité Augmentée",
    ],
  },
  {
    nom: "Haddad",
    prenom: "Fares",
    gender: "male",
    email: "fares.haddad@example.com",
    "numero de telephone": "0544906652",
    "Date de naissance": "1990-07-13",
    grade: "Professeur",
    availability_prof: ["mardi", "samedi", "lundi", "jeudi"],
    modules: [
      "Concepts Avancés du Génie Logiciel",
      "analyse 3",
      "Représentation de connaissances et raisonnement",
    ],
  },
  {
    nom: "Bougara",
    prenom: "Adil",
    gender: "male",
    email: "adil.bougara@example.com",
    "numero de telephone": "0577136439",
    "Date de naissance": "1980-01-05",
    grade: "Maître Assistant Classe B",
    availability_prof: ["samedi", "lundi", "dimanche"],
    modules: [
      "Réseaux Mobiles",
      "anglais",
      "physique",
      "Théorie de l’info. caractérisation de la transmission",
    ],
  },
  {
    nom: "Haddad",
    prenom: "Hamza",
    gender: "male",
    email: "hamza.haddad@example.com",
    "numero de telephone": "0699466468",
    "Date de naissance": "1987-09-06",
    grade: "Professeur",
    availability_prof: ["lundi", "dimanche"],
    modules: [
      "Electronique analogique",
      "Administration et Gestion des grilles de calcul",
      "Réseaux et communication sans fil",
      "algo 1",
    ],
  },
  {
    nom: "Chaker",
    prenom: "Abdourahman",
    gender: "male",
    email: "abdourahman.chaker@example.com",
    "numero de telephone": "0785424818",
    "Date de naissance": "1995-01-05",
    grade: "Maître Assistant Classe A",
    availability_prof: ["mercredi", "samedi", "mardi", "jeudi"],
    modules: [
      "BDABD : Bases de Données Avancées et Big Data",
      "Systèmes d’Information Coopératifs",
      "logique",
      "Modélisation des systèmes communicants",
    ],
  },
  {
    nom: "Afifi",
    prenom: "Abdelkader",
    gender: "male",
    email: "abdelkader.afifi@example.com",
    "numero de telephone": "0639290990",
    "Date de naissance": "1966-11-24",
    grade: "Doctorant",
    availability_prof: ["samedi", "jeudi", "mercredi", "mardi"],
    modules: [
      "Imagerie Médicale et Parallélisme",
      "Méthodologie et Processus de Développement de Logiciels",
      "Théorie de l’ordonnancement",
    ],
  },
  {
    nom: "Abdeslam",
    prenom: "Ziad",
    gender: "male",
    email: "ziad.abdeslam@example.com",
    "numero de telephone": "0554426292",
    "Date de naissance": "1964-09-20",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["lundi", "samedi", "dimanche"],
    modules: [
      "Gestion de Projets de Logiciels",
      "anglais",
      "anglais",
      "anglais",
    ],
  },
  {
    nom: "Berrada",
    prenom: "Nabil",
    gender: "male",
    email: "nabil.berrada@example.com",
    "numero de telephone": "0676941320",
    "Date de naissance": "1993-08-17",
    grade: "Maître Assistant Classe A",
    availability_prof: ["jeudi", "samedi", "mercredi", "mardi"],
    modules: [
      "Systèmes Décisionnels et Entrepôts",
      "Entreprenariat",
      "Architectures des réseaux informatiques",
      "Représentation de connaissances et raisonnement",
    ],
  },
  {
    nom: "Boudjema",
    prenom: "Aziz",
    gender: "male",
    email: "aziz.boudjema@example.com",
    "numero de telephone": "0617171468",
    "Date de naissance": "1982-12-08",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["jeudi", "dimanche"],
    modules: [
      "si",
      "Recherche d’information",
      "Introduction à la sécurité informatique",
    ],
  },
  {
    nom: "Benkirane",
    prenom: "Amar",
    gender: "male",
    email: "amar.benkirane@example.com",
    "numero de telephone": "0524498798",
    "Date de naissance": "1968-10-10",
    grade: "Maître Assistant Classe A",
    availability_prof: ["jeudi", "lundi", "mercredi", "dimanche"],
    modules: [
      "Arithmétique modulaire",
      "Représentation des Connaissances",
      "anglais",
      "strm",
    ],
  },
  {
    nom: "Boussalem",
    prenom: "Anissa",
    gender: "female",
    email: "anissa.boussalem@example.com",
    "numero de telephone": "0771017121",
    "Date de naissance": "1973-09-04",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["jeudi", "mercredi", "mardi", "dimanche"],
    modules: [
      "Programmation par contraintes",
      "Réseaux et communication sans fil",
      "Architectures Avancées",
      "Architecture et Administration de SGBD",
    ],
  },
  {
    nom: "Aziz",
    prenom: "Yasmine",
    gender: "female",
    email: "yasmine.aziz@example.com",
    "numero de telephone": "0657603463",
    "Date de naissance": "1985-06-05",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["mercredi", "mardi", "samedi"],
    modules: [
      "Programmation par contraintes",
      "Traitement automatique du langage naturel",
      "Méthodologie et Processus de Développement de Logiciels",
    ],
  },
  {
    nom: "Bouchaib",
    prenom: "Ayman",
    gender: "male",
    email: "ayman.bouchaib@example.com",
    "numero de telephone": "0795085674",
    "Date de naissance": "1968-02-10",
    grade: "Maître Assistant Classe A",
    availability_prof: ["mercredi", "lundi"],
    modules: ["anglais", "anglais", "Calcul Embarqué", "Vision artificielle"],
  },
  {
    nom: "Daghari",
    prenom: "Imad",
    gender: "male",
    email: "imad.daghari@example.com",
    "numero de telephone": "0574922257",
    "Date de naissance": "1978-11-21",
    grade: "Maître Assistant Classe B",
    availability_prof: ["dimanche", "mardi"],
    modules: [
      "Réseaux et communication sans fil",
      "Représentation des Connaissances",
      "Programmation Multi-Cœurs",
      "Système d’exploitation 2",
    ],
  },
  {
    nom: "Aziz",
    prenom: "Ali",
    gender: "male",
    email: "ali.aziz@example.com",
    "numero de telephone": "0599170419",
    "Date de naissance": "1997-01-04",
    grade: "Maître Assistant Classe A",
    availability_prof: ["samedi", "jeudi", "mardi", "lundi"],
    modules: [
      "anglais",
      "poo",
      "strm",
      "anadiss ( Analyse discriminante et segmentation )",
    ],
  },
  {
    nom: "Attar",
    prenom: "Fathi",
    gender: "male",
    email: "fathi.attar@example.com",
    "numero de telephone": "0589347162",
    "Date de naissance": "1965-04-28",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["mercredi", "mardi", "lundi"],
    modules: ["si 2", "anglais", "Calcul parallèle et grilles de calcul"],
  },
  {
    nom: "Afifi",
    prenom: "Mohamed",
    gender: "male",
    email: "mohamed.afifi@example.com",
    "numero de telephone": "0692175884",
    "Date de naissance": "1972-01-26",
    grade: "Doctorant",
    availability_prof: ["samedi", "mercredi", "mardi", "jeudi"],
    modules: ["TCE", "Systèmes d’exploitation", "Electronique numérique"],
  },
  {
    nom: "Djouder",
    prenom: "Amar",
    gender: "male",
    email: "amar.djouder@example.com",
    "numero de telephone": "0593629627",
    "Date de naissance": "1978-08-14",
    grade: "Professeur",
    availability_prof: ["jeudi", "mercredi", "dimanche", "samedi"],
    modules: [
      "SPS : Système et Programmation de Scripts",
      "Téléphonie, Téléphonie mobile et IP",
      "anglais",
      "MCA: Méthodes Conceptuelles d’Analyse",
    ],
  },
  {
    nom: "Aziz",
    prenom: "Amar",
    gender: "male",
    email: "amar.aziz@example.com",
    "numero de telephone": "0521723110",
    "Date de naissance": "1985-09-18",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["jeudi", "dimanche"],
    modules: [
      "Systèmes embarqués et applications en environnement mobile",
      "DESIN : Décision dans l’incertain",
      "Complexité algorithmique",
    ],
  },
  {
    nom: "Bouhani",
    prenom: "Leïla",
    gender: "female",
    email: "leïla.bouhani@example.com",
    "numero de telephone": "0770734005",
    "Date de naissance": "1998-12-09",
    grade: "Doctorant",
    availability_prof: ["samedi", "mardi", "jeudi"],
    modules: [
      "Data Mining",
      "BIOMATH : Biomathématique",
      "Théorie des graphes",
      "Architecture et administration des réseaux",
    ],
  },
  {
    nom: "Bahloul",
    prenom: "Abderahman",
    gender: "male",
    email: "abderahman.bahloul@example.com",
    "numero de telephone": "0649487269",
    "Date de naissance": "1987-08-01",
    grade: "Maître Assistant Classe B",
    availability_prof: ["jeudi", "mardi"],
    modules: [
      "anadiss ( Analyse discriminante et segmentation )",
      "Visualisation de données",
      "Modélisation et évaluation des performances des systèmes",
    ],
  },
  {
    nom: "Bentaleb",
    prenom: "Ameen",
    gender: "male",
    email: "ameen.bentaleb@example.com",
    "numero de telephone": "0769406167",
    "Date de naissance": "1992-10-28",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mercredi", "dimanche", "mardi", "lundi"],
    modules: [
      "Vision artificielle",
      "OPTDIS : Optimisation discrète",
      "Réseaux sans fil",
      "algo 1",
    ],
  },
  {
    nom: "Cherif",
    prenom: "Rania",
    gender: "female",
    email: "rania.cherif@example.com",
    "numero de telephone": "0531562447",
    "Date de naissance": "1966-07-31",
    grade: "Doctorant",
    availability_prof: ["mardi", "samedi", "dimanche", "jeudi"],
    modules: [
      "Syst. de communication analogiques et numériques",
      "Electronique numérique",
      "Communication Multimédia",
      "si 2",
    ],
  },
  {
    nom: "Baladi",
    prenom: "Jamal",
    gender: "male",
    email: "jamal.baladi@example.com",
    "numero de telephone": "0768003149",
    "Date de naissance": "1969-09-21",
    grade: "Maître Assistant Classe B",
    availability_prof: ["dimanche", "mercredi", "jeudi", "mardi"],
    modules: [
      "Architecture des Bases de données",
      "Résolution de problèmes",
      "Concepts Avancés du Génie Logiciel",
    ],
  },
  {
    nom: "Bennani",
    prenom: "Abdallah",
    gender: "male",
    email: "abdallah.bennani@example.com",
    "numero de telephone": "0658198788",
    "Date de naissance": "1977-03-12",
    grade: "Professeur",
    availability_prof: ["lundi", "mardi", "jeudi"],
    modules: ["anglais", "Algorithmique et complexité", "TCE"],
  },
  {
    nom: "Bahri",
    prenom: "Chaima",
    gender: "female",
    email: "chaima.bahri@example.com",
    "numero de telephone": "0564123715",
    "Date de naissance": "1964-07-23",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["mardi", "dimanche", "lundi", "jeudi"],
    modules: [
      "Architecture des Bases de données",
      "SPS : Système et Programmation de Scripts",
      "Systèmes d’exploitation",
      "BIOGEN : Bioinfo et Génomique",
    ],
  },
  {
    nom: "Hattab",
    prenom: "Anissa",
    gender: "female",
    email: "anissa.hattab@example.com",
    "numero de telephone": "0672875265",
    "Date de naissance": "1972-02-01",
    grade: "Professeur",
    availability_prof: ["jeudi", "mardi", "mercredi"],
    modules: [
      "algebre 3",
      "Représentation de connaissances et raisonnement 2",
      "anglais",
    ],
  },
  {
    nom: "Bounoua",
    prenom: "Sofia",
    gender: "female",
    email: "sofia.bounoua@example.com",
    "numero de telephone": "0754098652",
    "Date de naissance": "1987-05-28",
    grade: "Professeur",
    availability_prof: ["dimanche", "mardi", "samedi"],
    modules: [
      "Assurance Qualité des Logiciels",
      "Transmissions réseaux et codage d’information",
      "Méthodes pratiques et outils de détection d’intrusions",
    ],
  },
  {
    nom: "Benmoussa",
    prenom: "Akram",
    gender: "male",
    email: "akram.benmoussa@example.com",
    "numero de telephone": "0546393033",
    "Date de naissance": "1969-11-28",
    grade: "Doctorant",
    availability_prof: ["samedi", "jeudi"],
    modules: [
      "Programmation réseau",
      "anglais",
      "Concepts Avancés du Génie Logiciel",
    ],
  },
  {
    nom: "El",
    prenom: "Taha",
    gender: "male",
    email: "taha.el@example.com",
    "numero de telephone": "0783224570",
    "Date de naissance": "1997-07-18",
    grade: "Maître Assistant Classe B",
    availability_prof: ["samedi", "lundi"],
    modules: [
      "SPS : Système et Programmation de Scripts",
      "physique",
      "Génie Logiciel et POO",
    ],
  },
  {
    nom: "Hadjadj",
    prenom: "Nasser",
    gender: "male",
    email: "nasser.hadjadj@example.com",
    "numero de telephone": "0747087518",
    "Date de naissance": "1997-11-26",
    grade: "Maître Assistant Classe B",
    availability_prof: ["samedi", "lundi"],
    modules: [
      "sfsd",
      "Programmation Multi-Cœurs",
      "Représentation de connaissances et raisonnement",
      "algo 3",
    ],
  },
  {
    nom: "Aggoune",
    prenom: "Hicham",
    gender: "male",
    email: "hicham.aggoune@example.com",
    "numero de telephone": "0758782548",
    "Date de naissance": "1996-10-21",
    grade: "Professeur",
    availability_prof: ["samedi", "mercredi", "jeudi"],
    modules: [
      "Gestion de Projet de Développement de Logiciels",
      "Calcul Embarqué",
      "Programmation Multi-Cœurs",
    ],
  },
  {
    nom: "Bouhaddi",
    prenom: "Basma",
    gender: "female",
    email: "basma.bouhaddi@example.com",
    "numero de telephone": "0747623420",
    "Date de naissance": "1997-02-01",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["mardi", "jeudi"],
    modules: [
      "Compilation : génération du code et optimisation",
      "Systèmes d’exploitation",
      "anglais",
      "physique",
    ],
  },
  {
    nom: "Hafsi",
    prenom: "Nasser",
    gender: "male",
    email: "nasser.hafsi@example.com",
    "numero de telephone": "0578288812",
    "Date de naissance": "1998-02-07",
    grade: "Professeur",
    availability_prof: ["dimanche", "jeudi"],
    modules: [
      "Réseaux et Protocoles",
      "archi 1",
      "compilation",
      "Gestion de projet",
    ],
  },
  {
    nom: "Bouras",
    prenom: "Hafsa",
    gender: "female",
    email: "hafsa.bouras@example.com",
    "numero de telephone": "0748126432",
    "Date de naissance": "1977-05-17",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["dimanche", "jeudi", "mercredi", "lundi"],
    modules: [
      "Architecture et Administration de SGBD",
      "Stratégie de sécurité pour l’aide à la décision",
      "Architecture des Bases de données",
      "algebre",
    ],
  },
  {
    nom: "Bou",
    prenom: "Elias",
    gender: "male",
    email: "elias.bou@example.com",
    "numero de telephone": "0585327389",
    "Date de naissance": "1967-12-30",
    grade: "Maître Assistant Classe B",
    availability_prof: ["mercredi", "lundi", "dimanche", "mardi"],
    modules: [
      "BIOGEN : Bioinfo et Génomique",
      "Complexité algorithmique",
      "Recherche d’information",
    ],
  },
  {
    nom: "Bendjeddou",
    prenom: "Adil",
    gender: "male",
    email: "adil.bendjeddou@example.com",
    "numero de telephone": "0747195651",
    "Date de naissance": "1970-04-11",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["jeudi", "mardi"],
    modules: [
      "Génie Logiciel 2",
      "Réseaux sans fil",
      "Bases de Données 2",
      "Gestion de projet",
    ],
  },
  {
    nom: "Chelabi",
    prenom: "Anissa",
    gender: "female",
    email: "anissa.chelabi@example.com",
    "numero de telephone": "0765988548",
    "Date de naissance": "1967-09-23",
    grade: "Professeur",
    availability_prof: ["jeudi", "mardi", "lundi", "samedi"],
    modules: [
      "BIOMATH : Biomathématique",
      "SE: Système Embarqués",
      "Bases de Données 2",
    ],
  },
  {
    nom: "Amrani",
    prenom: "Adel",
    gender: "male",
    email: "adel.amrani@example.com",
    "numero de telephone": "0566749070",
    "Date de naissance": "1974-01-10",
    grade: "Maître Assistant Classe B",
    availability_prof: ["dimanche", "mardi"],
    modules: [
      "Veille technologique et Bases de données avancées",
      "FD2: Fouille de Données2",
      "Architecture et Administration de bases de Données",
    ],
  },
  {
    nom: "Bentaleb",
    prenom: "Hicham",
    gender: "male",
    email: "hicham.bentaleb@example.com",
    "numero de telephone": "0790367935",
    "Date de naissance": "1968-05-16",
    grade: "Doctorant",
    availability_prof: ["lundi", "samedi"],
    modules: [
      "Arithmétique modulaire",
      "anglais",
      "BIOSTAT : Biostatistique",
      "poo",
    ],
  },
  {
    nom: "Daghari",
    prenom: "Zainab",
    gender: "female",
    email: "zainab.daghari@example.com",
    "numero de telephone": "0632793466",
    "Date de naissance": "1981-12-25",
    grade: "Doctorant",
    availability_prof: ["lundi", "jeudi", "samedi", "mercredi"],
    modules: [
      "Techniques de modélisation en traitement du signal",
      "Synthèses d’images",
      "Génie Logiciel 2",
    ],
  },
  {
    nom: "Chakir",
    prenom: "Samira",
    gender: "female",
    email: "samira.chakir@example.com",
    "numero de telephone": "0788787824",
    "Date de naissance": "1980-04-19",
    grade: "Maître Assistant Classe B",
    availability_prof: ["samedi", "mercredi", "lundi", "mardi"],
    modules: [
      "Architecture et Administration de bases de Données",
      "algo 1",
      "sfsd",
    ],
  },
  {
    nom: "Bouhaddi",
    prenom: "Zainab",
    gender: "female",
    email: "zainab.bouhaddi@example.com",
    "numero de telephone": "0653958041",
    "Date de naissance": "1971-05-20",
    grade: "Doctorant",
    availability_prof: ["mercredi", "mardi", "jeudi", "samedi"],
    modules: [
      "Systèmes Décisionnels et Entrepôts",
      "FD2: Fouille de Données2",
      "Vision artificielle",
    ],
  },
  {
    nom: "Cherif",
    prenom: "Ismail",
    gender: "male",
    email: "ismail.cherif@example.com",
    "numero de telephone": "0562938794",
    "Date de naissance": "1974-08-08",
    grade: "Maître Assistant Classe A",
    availability_prof: ["mercredi", "dimanche", "mardi", "samedi"],
    modules: [
      "Modélisation des systèmes communicants",
      "SE: Système Embarqués",
      "anglais",
      "Audit de sécurité",
    ],
  },
  {
    nom: "Debchi",
    prenom: "Zineb",
    gender: "female",
    email: "zineb.debchi@example.com",
    "numero de telephone": "0680937647",
    "Date de naissance": "1989-03-28",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["dimanche", "lundi", "jeudi"],
    modules: [
      "Théorie de l’info. caractérisation de la transmission",
      "anglais",
      "BSD : Biométrie et Sécurisation de Données",
    ],
  },
  {
    nom: "Gharbi",
    prenom: "Laila",
    gender: "female",
    email: "laila.gharbi@example.com",
    "numero de telephone": "0556172125",
    "Date de naissance": "1971-04-29",
    grade: "Doctorant",
    availability_prof: ["dimanche", "samedi"],
    modules: [
      "compilation",
      "Syst. de communication analogiques et numériques",
      "anglais",
    ],
  },
  {
    nom: "Ghannouchi",
    prenom: "Ghada",
    gender: "female",
    email: "ghada.ghannouchi@example.com",
    "numero de telephone": "0687512856",
    "Date de naissance": "1982-05-21",
    grade: "Maître Assistant Classe B",
    availability_prof: ["jeudi", "dimanche", "lundi", "samedi"],
    modules: [
      "Architecture et Administration de SGBD",
      "algo 1",
      "Systèmes d’exploitation distribués",
    ],
  },
  {
    nom: "Hmida",
    prenom: "Sami",
    gender: "male",
    email: "sami.hmida@example.com",
    "numero de telephone": "0760088183",
    "Date de naissance": "1987-03-09",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["mercredi", "mardi", "jeudi", "dimanche"],
    modules: [
      "Architecture et Administration de bases de Données",
      "Programmation réseau",
      "Mathématiques appliquées (Analyse numérique)",
    ],
  },
  {
    nom: "Amrani",
    prenom: "Yasmine",
    gender: "female",
    email: "yasmine.amrani@example.com",
    "numero de telephone": "0625769183",
    "Date de naissance": "1977-09-14",
    grade: "Doctorant",
    availability_prof: ["mardi", "dimanche", "lundi", "jeudi"],
    modules: [
      "proba 2",
      "Traitement automatique du langage naturel",
      "Programmation Web",
    ],
  },
  {
    nom: "Chaker",
    prenom: "Adem",
    gender: "male",
    email: "adem.chaker@example.com",
    "numero de telephone": "0786304856",
    "Date de naissance": "1964-08-06",
    grade: "Professeur",
    availability_prof: ["mercredi", "dimanche", "mardi", "samedi"],
    modules: [
      "physique",
      "Construction de systèmes Parallèles",
      "Introduction à la sécurité informatique",
    ],
  },
  {
    nom: "Balouch",
    prenom: "Shahid",
    gender: "male",
    email: "shahid.balouch@example.com",
    "numero de telephone": "0685651093",
    "Date de naissance": "1968-11-18",
    grade: "Doctorant",
    availability_prof: ["dimanche", "mercredi"],
    modules: [
      "Systèmes Décisionnels et Entrepôts",
      "term",
      "Electronique numérique",
    ],
  },
  {
    nom: "Amrani",
    prenom: "Mohamed",
    gender: "male",
    email: "mohamed.amrani@example.com",
    "numero de telephone": "0776188125",
    "Date de naissance": "1979-08-27",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["jeudi", "samedi"],
    modules: [
      "Bureautique et Web",
      "DESIN : Décision dans l’incertain",
      "Téléphonie, Téléphonie mobile et IP",
      "BSD : Biométrie et Sécurisation de Données",
    ],
  },
  {
    nom: "Harb",
    prenom: "Youssef",
    gender: "male",
    email: "youssef.harb@example.com",
    "numero de telephone": "0661634636",
    "Date de naissance": "1996-02-02",
    grade: "Maître Assistant Classe A",
    availability_prof: ["lundi", "dimanche", "jeudi"],
    modules: [
      "Génie Logiciel 2",
      "anglais",
      "BIOGEN : Bioinfo et Génomique",
      "Systèmes d’exploitation distribués",
    ],
  },
  {
    nom: "Baladi",
    prenom: "Yasser",
    gender: "male",
    email: "yasser.baladi@example.com",
    "numero de telephone": "0679888504",
    "Date de naissance": "1975-08-29",
    grade: "Maître Assistant Classe A",
    availability_prof: ["mardi", "mercredi"],
    modules: [
      "Sécurité et contrôle du trafic réseau",
      "Bases de données Avancées",
      "Synthèses d’images",
    ],
  },
  {
    nom: "Bou",
    prenom: "Omar",
    gender: "male",
    email: "omar.bou@example.com",
    "numero de telephone": "0624580737",
    "Date de naissance": "1990-08-30",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["jeudi", "mercredi", "mardi"],
    modules: [
      "Construction de systèmes Parallèles",
      "Visualisation de données",
      "Systèmes Décisionnels et Entrepôts",
      "anglais",
    ],
  },
  {
    nom: "Abdo",
    prenom: "Hamid",
    gender: "male",
    email: "hamid.abdo@example.com",
    "numero de telephone": "0713676469",
    "Date de naissance": "1974-03-23",
    grade: "Maître Assistant Classe A",
    availability_prof: ["mercredi", "dimanche", "lundi"],
    modules: ["anglais", "Visualisation de données", "Réseaux et Protocoles"],
  },
  {
    nom: "Hmida",
    prenom: "Habib",
    gender: "male",
    email: "habib.hmida@example.com",
    "numero de telephone": "0595699139",
    "Date de naissance": "1965-03-20",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["lundi", "samedi", "jeudi"],
    modules: [
      "Concepts Avancés du Génie Logiciel",
      "Traitement automatique du langage naturel",
      "SOLO : Solveurs pour l’optimisation",
      "modelisation et simulation",
    ],
  },
  {
    nom: "Hamdi",
    prenom: "Mohamed",
    gender: "male",
    email: "mohamed.hamdi@example.com",
    "numero de telephone": "0748803281",
    "Date de naissance": "1966-12-19",
    grade: "Maître Assistant Classe A",
    availability_prof: ["samedi", "jeudi"],
    modules: [
      "SE: Système Embarqués",
      "SPS : Système et Programmation de Scripts",
      "Systèmes Décisionnels et Entrepôts",
      "Utilisation et administration des systèmes d’exploitation",
    ],
  },
  {
    nom: "Houari",
    prenom: "Ameen",
    gender: "male",
    email: "ameen.houari@example.com",
    "numero de telephone": "0532964156",
    "Date de naissance": "1989-03-21",
    grade: "Maître de Conférences Classe A",
    availability_prof: ["dimanche", "mercredi", "lundi"],
    modules: [
      "proba 2",
      "FD2: Fouille de Données2",
      "Arithmétique modulaire",
      "Représentation de connaissances et raisonnement 2",
    ],
  },
  {
    nom: "Debbeche",
    prenom: "Sofia",
    gender: "female",
    email: "sofia.debbeche@example.com",
    "numero de telephone": "0551766971",
    "Date de naissance": "1962-09-06",
    grade: "Maître de Conférences Classe B",
    availability_prof: ["mercredi", "mardi", "jeudi", "dimanche"],
    modules: [
      "Analyse numerique",
      "GPR : Gestion de Projet",
      "Gestion de projet",
      "Assurance Qualité des Logiciels",
    ],
  },
];
