import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/navbar";
import { AppContextProvider } from "./store/context";
import SessionWrapper from "./components/session-wrapper";
import { useSession, getSession } from "next-auth/react";
import { redirect } from "next/navigation";

const nunito = Nunito({
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={nunito.className}>
          <AppContextProvider>
            <div className="flex flex-col w-screen">
              <Navbar />
              {children}
              
            </div>
          </AppContextProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
